#!/usr/bin/python
# -*- coding:UTF-8 -*-
"""
Data Processing Processor
=========================
Processes data generated by crawlers, supporting:
- Continuous monitoring mode
- Asynchronous concurrent processing
- Graceful shutdown mechanism

Core improvements:
- Changed from blocking to continuous monitoring mode
- Supports background task execution
- Added graceful shutdown mechanism
"""
import asyncio
from asyncio import Queue
from typing import Union, Optional, List, Any
from enum import Enum, auto

from crawlo import Request, Item
from crawlo.exceptions import ItemDiscard
from crawlo.logging import get_logger
from crawlo.utils.async_lock import AsyncRLock


class ProcessorState(Enum):
    """Processor state"""
    IDLE = auto()       # Idle
    RUNNING = auto()    # Running
    STOPPING = auto()   # Stopping
    STOPPED = auto()    # Stopped


class Processor:
    """
    Data processor
    
    Continuously monitors queue, processes Request and Item.
    
    Features:
    - Continuous monitoring mode: continuously retrieves data from queue
    - Background execution: can run as background task
    - Graceful shutdown: supports waiting for current tasks to complete before shutdown
    - Statistics: tracks processing count
    
    Example:
        processor = Processor(crawler)
        await processor.open()
        
        # Method 1: Run in background
        task = processor.start()
        
        # Method 2: Manual processing
        await processor.enqueue(item)
        
        # Shutdown
        await processor.stop()
    """
    
    def __init__(self, crawler):
        """
        Initialize processor
        
        Args:
            crawler: Crawler instance
        """
        from crawlo.utils.misc import safe_get_config
        
        self.crawler = crawler
        self.queue: Queue = Queue()
        self.pipelines = None
        self.logger = get_logger(self.__class__.__name__)
        
        # Async-safe lock
        self._lock = AsyncRLock()
        
        # State management
        self._state = ProcessorState.IDLE
        self._task: Optional[asyncio.Task] = None
        self._stop_event = asyncio.Event()
        
        # Statistics
        self._processed_count = 0
        self._item_count = 0
        self._request_count = 0
        self._error_count = 0
        
        # Currently processing items (for graceful shutdown)
        # Using dict with id(item) as key
        self._processing: dict = {}
        self._processing_counter = 0
        
        # Configuration - use safe_get_config instead of getattr chain
        self._batch_size = safe_get_config(crawler.settings, 'PROCESSOR_BATCH_SIZE', 10, int)
        self._timeout = safe_get_config(crawler.settings, 'PROCESSOR_TIMEOUT', 1.0, float)
    
    async def open(self) -> None:
        """Initialize processor"""
        from crawlo.pipelines.manager import PipelineManager
        self.pipelines = await PipelineManager.from_crawler(self.crawler)
        
        # Call open_spider method of all pipelines (if exists)
        if self.crawler.spider and hasattr(self.pipelines, 'pipelines'):
            for pipeline in self.pipelines.pipelines:
                if hasattr(pipeline, 'open_spider'):
                    try:
                        await pipeline.open_spider(self.crawler.spider)
                    except Exception as e:
                        self.logger.error(f"Failed to open pipeline {pipeline.__class__.__name__}: {e}")
                        raise
        
        # Call open lifecycle method of middleware manager
        if hasattr(self.crawler, 'middleware_manager') and self.crawler.middleware_manager:
            try:
                await self.crawler.middleware_manager.open()
            except Exception as e:
                self.logger.error(f"Failed to open middleware manager: {e}")
                raise
        
        self.logger.debug("Processor initialized")
    
    async def start(self) -> asyncio.Task:
        """
        启动处理器（后台运行）
        
        Returns:
            asyncio.Task: 后台任务
        """
        if self._state == ProcessorState.RUNNING:
            self.logger.warning("Processor is already running")
            return self._task
        
        self._state = ProcessorState.RUNNING
        self._stop_event.clear()
        self._task = asyncio.create_task(self._run_loop())
        self.logger.debug("Processor started as background task")
        return self._task
    
    async def _run_loop(self) -> None:
        """
        持续监听循环
        
        不断从队列获取数据并处理，直到收到停止信号。
        """
        while not self._stop_event.is_set():
            try:
                # 使用超时避免永久阻塞
                try:
                    result = await asyncio.wait_for(self.queue.get(), timeout=self._timeout)
                except asyncio.TimeoutError:
                    # 超时后继续检查停止信号
                    continue
                
                await self._handle_result(result)
                
            except asyncio.CancelledError:
                self.logger.debug("Processor cancelled")
                break
            except Exception as e:
                self.logger.error(f"Error in processor loop: {e}")
                self._error_count += 1
        
        # 处理剩余队列
        await self._drain_queue()
        
        self._state = ProcessorState.STOPPED
        self.logger.debug(f"Processor stopped. Processed: {self._processed_count}")
    
    async def _handle_result(self, result: Union[Request, Item]) -> None:
        """
        处理单个结果（线程安全版本）
        
        Args:
            result: Request 或 Item
        """
        # 获取处理ID
        async with self._lock:
            processing_id = self._processing_counter
            self._processing_counter += 1
            self._processing[processing_id] = result
        
        try:
            if isinstance(result, Request):
                await self.crawler.engine.enqueue_request(result)
                async with self._lock:
                    self._request_count += 1
            elif isinstance(result, Item):
                await self._process_item(result)
                async with self._lock:
                    self._item_count += 1
            else:
                self.logger.warning(f"Unknown result type: {type(result)}")
            
            async with self._lock:
                self._processed_count += 1
            
        except Exception as e:
            async with self._lock:
                self._error_count += 1
            self.logger.error(f"Error processing {result}: {e}")
        finally:
            async with self._lock:
                self._processing.pop(processing_id, None)
    
    async def _process_item(self, item: Item) -> None:
        """
        处理 Item
        
        Args:
            item: 数据项
        """
        try:
            await self.pipelines.process_item(item=item)
        except ItemDiscard:
            # Item 被丢弃，正常流程
            pass
    
    async def _drain_queue(self) -> None:
        """排空队列中的剩余项"""
        while True:
            try:
                result = self.queue.get_nowait()
                await self._handle_result(result)
            except asyncio.QueueEmpty:
                break
    
    async def stop(self, timeout: float = 30.0) -> None:
        """
        停止处理器
        
        Args:
            timeout: 等待超时时间
        """
        if self._state == ProcessorState.STOPPED:
            return
        
        self._state = ProcessorState.STOPPING
        self._stop_event.set()
        
        if self._task and not self._task.done():
            try:
                await asyncio.wait_for(self._task, timeout=timeout)
            except asyncio.TimeoutError:
                self.logger.warning("Processor stop timeout, cancelling")
                self._task.cancel()
                try:
                    await self._task
                except asyncio.CancelledError:
                    pass
        
        self._state = ProcessorState.STOPPED
    
    async def enqueue(self, output: Union[Request, Item]) -> None:
        """
        将数据加入队列
        
        如果处理器未启动，会自动启动一次性处理。
        
        Args:
            output: Request 或 Item
        """
        await self.queue.put(output)
        
        # 如果处理器未运行，启动一次性处理
        if self._state == ProcessorState.IDLE:
            await self.process_once()
    
    async def process_once(self) -> None:
        """
        一次性处理队列中的所有数据
        
        处理完当前队列中的所有数据后返回。
        """
        while True:
            try:
                result = self.queue.get_nowait()
                await self._handle_result(result)
            except asyncio.QueueEmpty:
                break
    
    async def idle_async(self) -> bool:
        """
        异步安全地检查处理器是否空闲
        
        Returns:
            bool: 是否空闲
        """
        async with self._lock:
            return len(self._processing) == 0 and self.queue.empty()
    
    async def close(self) -> None:
        """
        关闭处理器并清理资源
        
        调用中间件和管道的 close 生命周期方法。
        """
        self.logger.debug("Closing processor...")
        
        # 关闭中间件管理器
        if hasattr(self.crawler, 'middleware_manager') and self.crawler.middleware_manager:
            try:
                await self.crawler.middleware_manager.close()
            except Exception as e:
                self.logger.warning(f"Error closing middleware manager: {e}")
        
        self.logger.debug("Processor closed")
    
    def idle(self) -> bool:
        """
        检查处理器是否空闲（简化版本，可能不够精确）
        
        Returns:
            bool: 是否空闲（队列为空且无正在处理的项）
        """
        return len(self) == 0 and len(self._processing) == 0
    
    def get_stats(self) -> dict:
        """
        获取统计信息
        
        Returns:
            dict: 统计信息字典
        """
        return {
            'state': self._state.name,
            'queue_size': len(self),
            'processing_count': len(self._processing),
            'processed_total': self._processed_count,
            'items_processed': self._item_count,
            'requests_processed': self._request_count,
            'errors': self._error_count,
        }
    
    def __len__(self) -> int:
        return self.queue.qsize()
    
    def __repr__(self) -> str:
        return f"<Processor: queue={len(self)}, state={self._state.name}>"
