site_name: Crawlo Documentation
site_url: https://crawlo.readthedocs.io/
site_description: An asynchronous distributed web crawling framework
site_author: Crawlo Team

repo_url: https://github.com/crawl-coder/Crawlo
edit_uri: ""

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

# 添加多语言支持
extra:
  alternate:
    - name: 中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en

nav:
  - 首页: 
    - 简介: index.md
    - 快速开始: modules/quickstart/index.md
    - 安装指南: modules/installation/index.md
  - 核心概念:
    - 架构概述: modules/architecture/index.md
    - 运行模式: modules/architecture/modes.md
    - 配置系统: modules/configuration/index.md
  - 核心模块:
    - 概述: modules/core/index.md
    - 引擎 (Engine): modules/core/engine.md
    - 调度器 (Scheduler): modules/core/scheduler.md
    - 处理器 (Processor): modules/core/processor.md
    - 爬虫基类 (Spider): modules/core/spider.md
  - 功能模块:
    - 下载器 (Downloader):
      - 概述: modules/downloader/index.md
      - AioHttpDownloader: modules/downloader/aiohttp.md
      - HttpXDownloader: modules/downloader/httpx.md
      - CurlCffiDownloader: modules/downloader/curl_cffi.md
      - SeleniumDownloader: modules/downloader/selenium.md
      - PlaywrightDownloader: modules/downloader/playwright.md
    - 队列 (Queue):
      - 概述: modules/queue/index.md
      - QueueManager: modules/queue/manager.md
      - 内存队列: modules/queue/memory.md
      - Redis队列: modules/queue/redis.md
    - 过滤器 (Filter):
      - 概述: modules/filter/index.md
      - BaseFilter: modules/filter/base.md
      - 内存过滤器: modules/filter/memory.md
      - Redis过滤器: modules/filter/redis.md
      - Bloom过滤器: modules/filter/bloom.md
    - 中间件 (Middleware):
      - 概述: modules/middleware/index.md
      - MiddlewareManager: modules/middleware/manager.md
      - 内置中间件: modules/middleware/built_in.md
      - 自定义中间件: modules/middleware/custom.md
      - 代理中间件: modules/middleware/proxy.md
    - 管道 (Pipeline):
      - 概述: modules/pipeline/index.md
      - PipelineManager: modules/pipeline/manager.md
      - 内置管道: modules/pipeline/built_in.md
      - 自定义管道: modules/pipeline/custom.md
    - 扩展 (Extension):
      - 概述: modules/extension/index.md
      - ExtensionManager: modules/extension/manager.md
      - 内置扩展: modules/extension/built_in.md
      - 自定义扩展: modules/extension/custom.md
  - 命令行工具:
    - CLI 概述: modules/cli/index.md
    - startproject: modules/cli/startproject.md
    - genspider: modules/cli/genspider.md
    - run: modules/cli/run.md
    - list: modules/cli/list.md
    - check: modules/cli/check.md
    - stats: modules/cli/stats.md
  - 高级主题:
    - 分布式部署: modules/advanced/distributed.md
    - 性能优化: modules/advanced/performance.md
    - 故障排除: modules/advanced/troubleshooting.md
    - 最佳实践: modules/advanced/best_practices.md
  - 教程:
    - 创建第一个爬虫: tutorials/first_spider.md
    - 分布式爬虫: tutorials/distributed_crawling.md
  - 详细文档:
    - 概述: api/index.md
    - crawlo: api/crawlo___init__.md
    - crawlo.config: api/crawlo_config.md
    - crawlo.config_validator: api/crawlo_config_validator.md
    - crawlo.crawler: api/crawlo_crawler.md
    - crawlo.spider: api/crawlo_spider___init__.md
    - crawlo.request: api/crawlo_network_request.md
    - crawlo.response: api/crawlo_network_response.md
    - crawlo.items: api/crawlo_items_items.md
    - crawlo.pipelines: api/crawlo_pipelines.md
    - crawlo.pipelines.RedisDedupPipeline: api/crawlo_pipelines_redis_dedup_pipeline.md
    - crawlo.pipelines.MemoryDedupPipeline: api/crawlo_pipelines_memory_dedup_pipeline.md
    - crawlo.pipelines.BloomDedupPipeline: api/crawlo_pipelines_bloom_dedup_pipeline.md
    - crawlo.pipelines.DatabaseDedupPipeline: api/crawlo_pipelines_database_dedup_pipeline.md
    - crawlo.pipelines.ConsolePipeline: api/crawlo_pipelines_console_pipeline.md
    - crawlo.pipelines.JsonPipeline: api/crawlo_pipelines_json_pipeline.md
    - crawlo.pipelines.CsvPipeline: api/crawlo_pipelines_csv_pipeline.md
    - crawlo.pipelines.AsyncmyMySQLPipeline: api/crawlo_pipelines_mysql_pipeline.md
    - crawlo.pipelines.MongoPipeline: api/crawlo_pipelines_mongo_pipeline.md
    - crawlo.middleware: api/crawlo_middleware.md
    - crawlo.extensions: api/crawlo_extension.md
    - crawlo.filters: api/crawlo_filters___init__.md
    - crawlo.downloader: api/crawlo_downloader___init__.md
    - crawlo.scheduler: api/crawlo_core_scheduler.md
    - crawlo.queues: api/crawlo_queue___init__.md
    - crawlo.utils: api/crawlo_utils_log.md

plugins:
  - search

# Extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg