services:
  redis-master:
    image: redis:7
    container_name: crawlo-redis-master
    command: ["redis-server", "--appendonly", "yes"]
    ports: ["6379:6379"]

  redis-replica:
    image: redis:7
    container_name: crawlo-redis-replica
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]
    depends_on:
      - redis-master

  sentinel-1:
    image: redis:7
    container_name: crawlo-redis-sentinel-1
    command: >
      redis-server --port 26379 --sentinel
      --sentinel monitor mymaster redis-master 6379 2
      --sentinel down-after-milliseconds mymaster 5000
      --sentinel failover-timeout mymaster 15000
    depends_on:
      - redis-master
      - redis-replica
    ports: ["26379:26379"]

  sentinel-2:
    image: redis:7
    container_name: crawlo-redis-sentinel-2
    command: >
      redis-server --port 26379 --sentinel
      --sentinel monitor mymaster redis-master 6379 2
      --sentinel down-after-milliseconds mymaster 5000
      --sentinel failover-timeout mymaster 15000
    depends_on:
      - redis-master
      - redis-replica

  sentinel-3:
    image: redis:7
    container_name: crawlo-redis-sentinel-3
    command: >
      redis-server --port 26379 --sentinel
      --sentinel monitor mymaster redis-master 6379 2
      --sentinel down-after-milliseconds mymaster 5000
      --sentinel failover-timeout mymaster 15000
    depends_on:
      - redis-master
      - redis-replica
