CREATE TABLE `listed_statement_of_cash_flows` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `pmid` VARCHAR(32) NOT NULL COMMENT 'md5(stock_code+report_date)',
  `stock_code` VARCHAR(20) NOT NULL COMMENT '股票代码',
  `stock_name` VARCHAR(255) NOT NULL COMMENT '股票简称',
  `security_code` VARCHAR(20) DEFAULT NULL COMMENT '证券代码（不含交易所后缀）',
  `org_code` VARCHAR(30) DEFAULT NULL COMMENT '组织代码',
  `org_type` VARCHAR(255) DEFAULT NULL COMMENT '组织类型',
  `report_date` DATE NOT NULL COMMENT '报告日期',
  `report_type` VARCHAR(255) DEFAULT NULL COMMENT '报告类型',
  `report_date_name` VARCHAR(255) DEFAULT NULL COMMENT '报告日期名称',
  `security_type_code` VARCHAR(10) DEFAULT NULL COMMENT '证券类型代码',
  `notice_date` DATE DEFAULT NULL COMMENT '公告日期',
  `update_date` DATE DEFAULT NULL COMMENT '更新日期',
  `currency` VARCHAR(255) DEFAULT NULL COMMENT '货币单位',

  -- ========== 经营活动现金流量 ==========
  `sales_services` DECIMAL(20,4) DEFAULT NULL COMMENT '销售商品、提供劳务收到的现金',
  `deposit_interbank_add` DECIMAL(20,4) DEFAULT NULL COMMENT '吸收存款及同业存放款项增加额',
  `loan_pbc_add` DECIMAL(20,4) DEFAULT NULL COMMENT '向中央银行借款增加额',
  `ofi_bf_add` DECIMAL(20,4) DEFAULT NULL COMMENT '向其他金融机构拆入资金增加额',
  `receive_origic_premium` DECIMAL(20,4) DEFAULT NULL COMMENT '收到原保险保费的现金',
  `receive_reinsure_net` DECIMAL(20,4) DEFAULT NULL COMMENT '收到再保险业务净现金',
  `insured_invest_add` DECIMAL(20,4) DEFAULT NULL COMMENT '保户投资款增加额',
  `disposal_tfa_add` DECIMAL(20,4) DEFAULT NULL COMMENT '处置交易性金融资产增加额',
  `receive_interest_commission` DECIMAL(20,4) DEFAULT NULL COMMENT '收到利息及手续费的现金',
  `borrow_fund_add` DECIMAL(20,4) DEFAULT NULL COMMENT '借入资金增加额',
  `loan_advance_reduce` DECIMAL(20,4) DEFAULT NULL COMMENT '贷款及垫款减少额',
  `repo_business_add` DECIMAL(20,4) DEFAULT NULL COMMENT '回购业务增加额',
  `receive_tax_refund` DECIMAL(20,4) DEFAULT NULL COMMENT '收到的税收返还',
  `receive_other_operate` DECIMAL(20,4) DEFAULT NULL COMMENT '收到其他与经营活动有关的现金',
  `operate_inflow_other` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动现金流入其他项',
  `operate_inflow_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动现金流入余额',
  `total_operate_inflow` DECIMAL(24,4) DEFAULT NULL COMMENT '经营活动现金流入总额/经营活动现金流入小计',
  `buy_services` DECIMAL(20,4) DEFAULT NULL COMMENT '购买商品、接受劳务支付的现金',
  `loan_advance_add` DECIMAL(20,4) DEFAULT NULL COMMENT '贷款及垫款增加额',
  `pbc_interbank_add` DECIMAL(20,4) DEFAULT NULL COMMENT '存放中央银行及同业款项增加额',
  `pay_origic_compensate` DECIMAL(20,4) DEFAULT NULL COMMENT '支付原保险赔付的现金',
  `pay_interest_commission` DECIMAL(20,4) DEFAULT NULL COMMENT '支付利息及手续费的现金',
  `pay_policy_bonus` DECIMAL(20,4) DEFAULT NULL COMMENT '支付保单红利的现金',
  `pay_staff_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '支付给职工以及为职工支付的现金',
  `pay_all_tax` DECIMAL(20,4) DEFAULT NULL COMMENT '支付的各项税费',
  `pay_other_operate` DECIMAL(20,4) DEFAULT NULL COMMENT '支付其他与经营活动有关的现金',
  `operate_outflow_other` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动现金流出其他项',
  `operate_outflow_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动现金流出余额',
  `total_operate_outflow` DECIMAL(24,4) DEFAULT NULL COMMENT '经营活动现金流出总额',
  `operate_netcash_other` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动净现金流其他项',
  `operate_netcash_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动净现金流余额',
  `netcash_operate` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动产生的现金流量净额',

  -- ========== 投资活动现金流量 ==========
  `withdraw_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '收回投资收到的现金',
  `receive_invest_income` DECIMAL(20,4) DEFAULT NULL COMMENT '取得投资收益收到的现金',
  `disposal_long_asset` DECIMAL(20,4) DEFAULT NULL COMMENT '处置固定资产、无形资产和其他长期资产收回的现金净额',
  `disposal_subsidiary_other` DECIMAL(20,4) DEFAULT NULL COMMENT '处置子公司及其他营业单位收到的现金',
  `reduce_pledge_timedeposits` DECIMAL(20,4) DEFAULT NULL COMMENT '减少质押及定期存款收到的现金',
  `receive_other_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '收到其他与投资活动有关的现金',
  `invest_inflow_other` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动现金流入其他项',
  `invest_inflow_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动现金流入余额',
  `total_invest_inflow` DECIMAL(24,4) DEFAULT NULL COMMENT '投资活动现金流入总额/投资活动现金流入小计',
  `construct_long_asset` DECIMAL(20,4) DEFAULT NULL COMMENT '购建固定资产、无形资产和其他长期资产支付的现金',
  `invest_pay_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '投资支付的现金',
  `pledge_loan_add` DECIMAL(20,4) DEFAULT NULL COMMENT '质押贷款增加额',
  `obtain_subsidiary_other` DECIMAL(20,4) DEFAULT NULL COMMENT '取得子公司及其他营业单位支付的现金净额',
  `add_pledge_timedeposits` DECIMAL(20,4) DEFAULT NULL COMMENT '增加质押及定期存款支付的现金',
  `pay_other_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '支付其他与投资活动有关的现金',
  `invest_outflow_other` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动现金流出其他项',
  `invest_outflow_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动现金流出余额',
  `total_invest_outflow` DECIMAL(24,4) DEFAULT NULL COMMENT '投资活动现金流出总额/投资活动现金流出小计',
  `invest_netcash_other` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动净现金流其他项',
  `invest_netcash_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动净现金流余额',
  `netcash_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '投资活动产生的现金流量净额',

  -- ========== 筹资活动现金流量 ==========
  `accept_invest_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '吸收投资收到的现金',
  `subsidiary_accept_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '子公司吸收投资收到的现金',
  `receive_loan_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '取得借款收到的现金',
  `issue_bond` DECIMAL(20,4) DEFAULT NULL COMMENT '发行债券收到的现金',
  `receive_other_finance` DECIMAL(20,4) DEFAULT NULL COMMENT '收到其他与筹资活动有关的现金',
  `finance_inflow_other` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动现金流入其他项',
  `finance_inflow_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动现金流入余额',
  `total_finance_inflow` DECIMAL(24,4) DEFAULT NULL COMMENT '筹资活动现金流入总额',
  `pay_debt_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '偿还债务支付的现金',
  `assign_dividend_porfit` DECIMAL(20,4) DEFAULT NULL COMMENT '分配股利、利润或偿付利息支付的现金',
  `subsidiary_pay_dividend` DECIMAL(20,4) DEFAULT NULL COMMENT '子公司支付股利或利润的现金',
  `buy_subsidiary_equity` DECIMAL(20,4) DEFAULT NULL COMMENT '购买子公司股权支付的现金',
  `pay_other_finance` DECIMAL(20,4) DEFAULT NULL COMMENT '支付其他与筹资活动有关的现金',
  `subsidiary_reduce_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '子公司减少注册资本支付的现金',
  `finance_outflow_other` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动现金流出其他项',
  `finance_outflow_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动现金流出余额',
  `total_finance_outflow` DECIMAL(24,4) DEFAULT NULL COMMENT '筹资活动现金流出总额',
  `finance_netcash_other` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动净现金流其他项',
  `finance_netcash_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动净现金流余额',
  `netcash_finance` DECIMAL(20,4) DEFAULT NULL COMMENT '筹资活动产生的现金流量净额',

  -- ========== 现金及现金等价物净增加额 ==========
  `rate_change_effect` DECIMAL(20,4) DEFAULT NULL COMMENT '汇率变动对现金及现金等价物的影响',
  `cce_add_other` DECIMAL(20,4) DEFAULT NULL COMMENT '现金及现金等价物增加额其他项',
  `cce_add_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '现金及现金等价物增加额余额',
  `cce_add` DECIMAL(20,4) DEFAULT NULL COMMENT '现金及现金等价物净增加额',
  `begin_cce` DECIMAL(20,4) DEFAULT NULL COMMENT '期初现金及现金等价物余额',
  `end_cce_other` DECIMAL(20,4) DEFAULT NULL COMMENT '期末现金及现金等价物其他项',
  `end_cce_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '期末现金及现金等价物余额',
  `end_cce` DECIMAL(20,4) DEFAULT NULL COMMENT '期末现金及现金等价物总额',

  -- ========== 将净利润调节为经营活动现金流量 ==========
  `netprofit` DECIMAL(24,4) DEFAULT NULL COMMENT '净利润',
  `asset_impairment` DECIMAL(20,4) DEFAULT NULL COMMENT '资产减值准备',
  `fa_ir_depr` DECIMAL(20,4) DEFAULT NULL COMMENT '固定资产及投资性房地产折旧',
  `oilgas_biology_depr` DECIMAL(20,4) DEFAULT NULL COMMENT '油气资产及生物资产折旧',
  `ir_depr` DECIMAL(20,4) DEFAULT NULL COMMENT '投资性房地产折旧',
  `ia_amortize` DECIMAL(20,4) DEFAULT NULL COMMENT '无形资产摊销',
  `lpe_amortize` DECIMAL(20,4) DEFAULT NULL COMMENT '长期待摊费用摊销',
  `defer_income_amortize` DECIMAL(20,4) DEFAULT NULL COMMENT '递延收益摊销',
  `prepaid_expense_reduce` DECIMAL(20,4) DEFAULT NULL COMMENT '预付费用减少额',
  `accrued_expense_add` DECIMAL(20,4) DEFAULT NULL COMMENT '应计费用增加额',
  `disposal_longasset_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '处置固定资产、无形资产和其他长期资产的损失',
  `fa_scrap_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '固定资产报废损失',
  `fairvalue_change_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '公允价值变动损失',
  `finance_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '财务费用',
  `invest_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '投资损失',
  `defer_tax` DECIMAL(20,4) DEFAULT NULL COMMENT '递延所得税',
  `dt_asset_reduce` DECIMAL(20,4) DEFAULT NULL COMMENT '递延所得税资产减少额',
  `dt_liab_add` DECIMAL(20,4) DEFAULT NULL COMMENT '递延所得税负债增加额',
  `predict_liab_add` DECIMAL(20,4) DEFAULT NULL COMMENT '预计负债增加额',
  `inventory_reduce` DECIMAL(20,4) DEFAULT NULL COMMENT '存货减少额',
  `operate_rece_reduce` DECIMAL(20,4) DEFAULT NULL COMMENT '经营性应收项目减少额',
  `operate_payable_add` DECIMAL(20,4) DEFAULT NULL COMMENT '经营性应付项目增加额',
  `other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他调整项',
  `operate_netcash_othernote` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动净现金流其他调整项',
  `operate_netcash_balancenote` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动净现金流余额调整项',
  `netcash_operatenote` DECIMAL(20,4) DEFAULT NULL COMMENT '经营活动净现金流调整总额',

  -- ========== 其他 ==========
  `debt_transfer_capital` DECIMAL(20,4) DEFAULT NULL COMMENT '债务转为资本的现金',
  `convert_bond_1year` DECIMAL(20,4) DEFAULT NULL COMMENT '一年内到期的可转换公司债券',
  `finlease_obtain_fa` DECIMAL(20,4) DEFAULT NULL COMMENT '融资租赁取得的固定资产',
  `uninvolve_investfin_other` DECIMAL(20,4) DEFAULT NULL COMMENT '不涉及投资和筹资的现金其他项',
  `end_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '期末现金余额',
  `begin_cash` DECIMAL(20,4) DEFAULT NULL COMMENT '期初现金余额',
  `end_cash_equivalents` DECIMAL(20,4) DEFAULT NULL COMMENT '期末现金等价物余额',
  `begin_cash_equivalents` DECIMAL(20,4) DEFAULT NULL COMMENT '期初现金等价物余额',
  `cce_add_othernote` DECIMAL(20,4) DEFAULT NULL COMMENT '现金及现金等价物增加额其他调整项',
  `cce_add_balancenote` DECIMAL(20,4) DEFAULT NULL COMMENT '现金及现金等价物增加额余额调整项',
  `cce_addnote` DECIMAL(20,4) DEFAULT NULL COMMENT '现金及现金等价物增加额调整总额',

  -- ========== 同比增长率 ==========
  `sales_services_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '销售商品、提供劳务收到的现金同比',
  `deposit_interbank_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '吸收存款及同业存放款项增加额同比',
  `loan_pbc_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '向中央银行借款增加额同比',
  `ofi_bf_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '向其他金融机构拆入资金增加额同比',
  `receive_origic_premium_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到原保险保费的现金同比',
  `receive_reinsure_net_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到再保险业务净现金同比',
  `insured_invest_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '保户投资款增加额同比',
  `disposal_tfa_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '处置交易性金融资产增加额同比',
  `receive_interest_commission_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到利息及手续费的现金同比',
  `borrow_fund_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '借入资金增加额同比',
  `loan_advance_reduce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '贷款及垫款减少额同比',
  `repo_business_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '回购业务增加额同比',
  `receive_tax_refund_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到税费返还的现金同比',
  `receive_other_operate_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到其他与经营活动有关的现金同比',
  `operate_inflow_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动现金流入其他项同比',
  `operate_inflow_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动现金流入余额同比',
  `total_operate_inflow_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动现金流入总额同比',
  `buy_services_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '购买商品、接受劳务支付的现金同比',
  `loan_advance_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '贷款及垫款增加额同比',
  `pbc_interbank_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '存放中央银行及同业款项增加额同比',
  `pay_origic_compensate_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付原保险赔付的现金同比',
  `pay_interest_commission_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付利息及手续费的现金同比',
  `pay_policy_bonus_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付保单红利的现金同比',
  `pay_staff_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付给职工以及为职工支付的现金同比',
  `pay_all_tax_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付的各项税费同比',
  `pay_other_operate_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付其他与经营活动有关的现金同比',
  `operate_outflow_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动现金流出其他项同比',
  `operate_outflow_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动现金流出余额同比',
  `total_operate_outflow_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动现金流出总额同比',
  `operate_netcash_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动净现金流其他项同比',
  `operate_netcash_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动净现金流余额同比',
  `netcash_operate_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动产生的现金流量净额同比',
  `withdraw_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收回投资收到的现金同比',
  `receive_invest_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '取得投资收益收到的现金同比',
  `disposal_long_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '处置固定资产、无形资产等长期资产收到的现金同比',
  `disposal_subsidiary_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '处置子公司及其他营业单位收到的现金同比',
  `reduce_pledge_timedeposits_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '减少质押及定期存款收到的现金同比',
  `receive_other_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到其他与投资活动有关的现金同比',
  `invest_inflow_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动现金流入其他项同比',
  `invest_inflow_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动现金流入余额同比',
  `total_invest_inflow_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动现金流入总额同比',
  `construct_long_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '购建固定资产、无形资产等长期资产支付的现金同比',
  `invest_pay_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资支付的现金同比',
  `pledge_loan_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '质押贷款增加额同比',
  `obtain_subsidiary_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '取得子公司及其他营业单位支付的现金同比',
  `add_pledge_timedeposits_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '增加质押及定期存款支付的现金同比',
  `pay_other_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付其他与投资活动有关的现金同比',
  `invest_outflow_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动现金流出其他项同比',
  `invest_outflow_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动现金流出余额同比',
  `total_invest_outflow_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动现金流出总额同比',
  `invest_netcash_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动净现金流其他项同比',
  `invest_netcash_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动净现金流余额同比',
  `netcash_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资活动产生的现金流量净额同比',
  `accept_invest_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '吸收投资收到的现金同比',
  `subsidiary_accept_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '子公司吸收投资收到的现金同比',
  `receive_loan_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '取得借款收到的现金同比',
  `issue_bond_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '发行债券收到的现金同比',
  `receive_other_finance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '收到其他与筹资活动有关的现金同比',
  `finance_inflow_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动现金流入其他项同比',
  `finance_inflow_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动现金流入余额同比',
  `total_finance_inflow_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动现金流入总额同比',
  `pay_debt_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '偿还债务支付的现金同比',
  `assign_dividend_porfit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '分配股利、利润或偿付利息支付的现金同比',
  `subsidiary_pay_dividend_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '子公司支付股利或利润的现金同比',
  `buy_subsidiary_equity_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '购买子公司股权支付的现金同比',
  `pay_other_finance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '支付其他与筹资活动有关的现金同比',
  `subsidiary_reduce_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '子公司减少注册资本支付的现金同比',
  `finance_outflow_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动现金流出其他项同比',
  `finance_outflow_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动现金流出余额同比',
  `total_finance_outflow_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动现金流出总额同比',
  `finance_netcash_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动净现金流其他项同比',
  `finance_netcash_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动净现金流余额同比',
  `netcash_finance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '筹资活动产生的现金流量净额同比',
  `rate_change_effect_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '汇率变动对现金及现金等价物的影响同比',
  `cce_add_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金及现金等价物增加额其他项同比',
  `cce_add_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金及现金等价物增加额余额同比',
  `cce_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金及现金等价物净增加额同比',
  `begin_cce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期初现金及现金等价物余额同比',
  `end_cce_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期末现金及现金等价物其他项同比',
  `end_cce_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期末现金及现金等价物余额同比',
  `end_cce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期末现金及现金等价物总额同比',
  `netprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净利润同比',
  `asset_impairment_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资产减值准备同比',
  `fa_ir_depr_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '固定资产及投资性房地产折旧同比',
  `oilgas_biology_depr_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '油气资产及生物资产折旧同比',
  `ir_depr_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资性房地产折旧同比',
  `ia_amortize_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '无形资产摊销同比',
  `lpe_amortize_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期待摊费用摊销同比',
  `defer_income_amortize_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延收益摊销同比',
  `prepaid_expense_reduce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预付费用减少额同比',
  `accrued_expense_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应计费用增加额同比',
  `disposal_longasset_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '处置长期资产损失同比',
  `fa_scrap_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '固定资产报废损失同比',
  `fairvalue_change_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '公允价值变动损失同比',
  `finance_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '财务费用同比',
  `invest_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资损失同比',
  `defer_tax_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延所得税同比',
  `dt_asset_reduce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延所得税资产减少额同比',
  `dt_liab_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延所得税负债增加额同比',
  `predict_liab_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预计负债增加额同比',
  `inventory_reduce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '存货减少额同比',
  `operate_rece_reduce_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营性应收项目减少额同比',
  `operate_payable_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营性应付项目增加额同比',
  `other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他调整项同比',
  `operate_netcash_othernote_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动净现金流其他调整项同比',
  `operate_netcash_balancenote_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动净现金流余额调整项同比',
  `netcash_operatenote_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '经营活动净现金流调整总额同比',
  `debt_transfer_capital_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '债务转为资本的现金同比',
  `convert_bond_1year_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '一年内到期的可转换公司债券同比',
  `finlease_obtain_fa_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '融资租赁取得的固定资产同比',
  `uninvolve_investfin_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '不涉及投资和筹资的现金其他项同比',
  `end_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期末现金余额同比',
  `begin_cash_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期初现金余额同比',
  `end_cash_equivalents_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期末现金等价物余额同比',
  `begin_cash_equivalents_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '期初现金等价物余额同比',
  `cce_add_othernote_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金及现金等价物增加额其他调整项同比',
  `cce_add_balancenote_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金及现金等价物增加额余额调整项同比',
  `cce_addnote_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金及现金等价物增加额调整总额同比',

  -- ========== 审计意见 ==========
  `opinion_type` VARCHAR(255) DEFAULT NULL COMMENT '审计意见类型',
  `osopinion_type` VARCHAR(255) DEFAULT NULL COMMENT '其他审计意见类型',

  -- ========== 少数股东损益 ==========
  `minority_interest` DECIMAL(20,4) DEFAULT NULL COMMENT '少数股东损益',
  `minority_interest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '少数股东损益同比',

  -- ========== 使用权资产摊销 ==========
  `useright_asset_amortize` DECIMAL(20,4) DEFAULT NULL COMMENT '使用权资产摊销',
  `useright_asset_amortize_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '使用权资产摊销同比',

  -- ========== 系统字段 ==========
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',

  -- ========== 索引 ==========
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pmid` (`pmid`),
  INDEX `idx_stock_code` (`stock_code`),
  INDEX `idx_report_date` (`report_date`),
  INDEX `idx_stock_date` (`stock_code`, `report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上市公司-现金流量表';