CREATE TABLE `listed_balance_sheet_of_companies` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `pmid` VARCHAR(32) NOT NULL COMMENT 'md5(stock_code+report_date)',
  `stock_code` VARCHAR(20) NOT NULL COMMENT '股票代码',
  `stock_name` VARCHAR(255) NOT NULL COMMENT '股票简称',
  `report_date` DATE NOT NULL COMMENT '报告日期',

  -- ========== 资产项目 ========== 
  `monetary_funds` DECIMAL(20,4) DEFAULT NULL COMMENT '货币资金 (元)',
  `trading_financial_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '交易性金融资产 (元)',
  `derivative_financial_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '衍生金融资产 (元)',
  `note_accounts_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收票据及应收账款 (元)',
  `notes_receivable` DECIMAL(20,4) DEFAULT NULL COMMENT '其中应收票据 (元)',
  `accounts_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '其中应收帐款 (元)',
  `finance_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收款项融资 (元)',
  `prepaid_items` DECIMAL(20,4) DEFAULT NULL COMMENT '预付款项 (元)',
  `total_other_receivables` DECIMAL(24,4) DEFAULT NULL COMMENT '其他应收款合计 (元)',
  `receivable_dividends` DECIMAL(20,4) DEFAULT NULL COMMENT '其中应收股利 (元)',
  `inventory` DECIMAL(20,4) DEFAULT NULL COMMENT '存货 (元)',
  `contract_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '合同资产 (元)',
  `other_current_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '其他流动资产 (元)',
  `total_current_assets` DECIMAL(24,4) DEFAULT NULL COMMENT '流动资产合计 (元)',
  `other_noncurrent_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '其他非流动金融资产 (元)',
  `long_term_equity_investment` DECIMAL(20,4) DEFAULT NULL COMMENT '长期股权投资 (元)',
  `debt_investment` DECIMAL(20,4) DEFAULT NULL COMMENT '债权投资 (元)',
  `other_equity_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '其他权益工具投资 (元)',
  `investment_property` DECIMAL(20,4) DEFAULT NULL COMMENT '投资性房地产 (元)',
  `right_of_use_asset` DECIMAL(20,4) DEFAULT NULL COMMENT '使用权资产 (元)',
  `fixed_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '固定资产 (元)',
  `construction_in_progress` DECIMAL(20,4) DEFAULT NULL COMMENT '在建工程 (元)',
  `intangible_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '无形资产 (元)',
  `long_term_prepaid_expenses` DECIMAL(20,4) DEFAULT NULL COMMENT '长期待摊费用 (元)',
  `goodwill` DECIMAL(20,4) DEFAULT NULL COMMENT '商誉 (元)',
  `deferred_tax_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '递延所得税资产 (元)',
  `other_non_current_assets` DECIMAL(20,4) DEFAULT NULL COMMENT '其他非流动资产 (元)',
  `total_non_current_assets` DECIMAL(24,4) DEFAULT NULL COMMENT '非流动资产合计 (元)',
  `total_assets` DECIMAL(24,4) DEFAULT NULL COMMENT '资产总计 (元)',

  -- ========== 负债项目 ========== 
  `short_term_loans` DECIMAL(20,4) DEFAULT NULL COMMENT '短期借款 (元)',
  `note_accounts_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '应付票据及应付账款 (元)',
  `notes_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '其中应付票据 (元)',
  `accounts_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '其中应付账款 (元)',
  `advance_from_customers` DECIMAL(20,4) DEFAULT NULL COMMENT '预收款项 (元)',
  `contract_liabilities` DECIMAL(20,4) DEFAULT NULL COMMENT '合同负债 (元)',
  `employee_compensation` DECIMAL(20,4) DEFAULT NULL COMMENT '应付职工薪酬 (元)',
  `taxes_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '应交税费 (元)',
  `total_other_payables` DECIMAL(24,4) DEFAULT NULL COMMENT '其他应付款合计 (元)',
  `dividends_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '其中应付股利 (元)',
  `noncurrent_liab_1year` DECIMAL(20,4) DEFAULT NULL COMMENT '一年内到期的非流动负债 (元)',
  `other_current_liabilities` DECIMAL(20,4) DEFAULT NULL COMMENT '其他流动负债 (元)',
  `total_current_liabilities` DECIMAL(24,4) DEFAULT NULL COMMENT '流动负债合计 (元)',
  `lease_liabilities_long_term` DECIMAL(20,4) DEFAULT NULL COMMENT '租赁负债 (元)',
  `long_term_loans` DECIMAL(20,4) DEFAULT NULL COMMENT '长期借款 (元)',
  `lease_liabilities` DECIMAL(20,4) DEFAULT NULL COMMENT '租赁负债 (元)',
  `estimated_liabilities` DECIMAL(20,4) DEFAULT NULL COMMENT '预计负债 (元)',
  `deferred_revenue` DECIMAL(20,4) DEFAULT NULL COMMENT '递延收益 (元)',
  `defer_tax_liab` DECIMAL(20,4) DEFAULT NULL COMMENT '递延所得税负债 (元)',
  `total_noncurrent_liab` DECIMAL(24,4) DEFAULT NULL COMMENT '非流动负债合计 (元)',
  `total_liabilities` DECIMAL(24,4) DEFAULT NULL COMMENT '负债合计 (元)',

  -- ========== 股东权益项目 ========== 
  `paid_in_capital` DECIMAL(20,4) DEFAULT NULL COMMENT '实收资本 (或股本) (元)',
  `other_equity_instruments` DECIMAL(20,4) DEFAULT NULL COMMENT '其他权益工具 (元)',
  `capital_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '资本公积 (元)',
  `treasury_stock` DECIMAL(20,4) DEFAULT NULL COMMENT '减库存股 (元)',
  `other_compre_income` DECIMAL(20,4) DEFAULT NULL COMMENT '其他综合收益 (元)',
  `dedicated_reserves` DECIMAL(20,4) DEFAULT NULL COMMENT '专项储备 (元)',
  `surplus_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '盈余公积 (元)',
  `undistributed_profit` DECIMAL(20,4) DEFAULT NULL COMMENT '未分配利润 (元)',
  `total_parent_equity` DECIMAL(24,4) DEFAULT NULL COMMENT '归属于母公司股东权益总计 (元)',
  `minority_interest` DECIMAL(20,4) DEFAULT NULL COMMENT '少数股东权益 (元)',
  `total_equity` DECIMAL(24,4) DEFAULT NULL COMMENT '股东权益合计 (元)',
  `total_liabilities_and_equity` DECIMAL(24,4) DEFAULT NULL COMMENT '负债和股东权益总计 (元)',

  -- ========== 审计意见 ========== 
  `audit_opinion_domestic` VARCHAR(255) DEFAULT NULL COMMENT '审计意见 (境内)',

  -- ========== 额外字段 ========== 
  `security_code` VARCHAR(20) DEFAULT NULL COMMENT '证券代码',
  `org_code` VARCHAR(30) DEFAULT NULL COMMENT '机构代码',
  `org_type` VARCHAR(255) DEFAULT NULL COMMENT '机构类型',
  `report_type` VARCHAR(255) DEFAULT NULL COMMENT '报告类型',
  `report_date_name` VARCHAR(255) DEFAULT NULL COMMENT '报告日期名称',
  `security_type_code` VARCHAR(10) DEFAULT NULL COMMENT '证券类型代码',
  `notice_date` DATE DEFAULT NULL COMMENT '公告日期',
  `update_date` DATE DEFAULT NULL COMMENT '更新日期',
  `currency` VARCHAR(255) DEFAULT NULL COMMENT '货币单位',
  `accept_deposit_interbank` DECIMAL(20,4) DEFAULT NULL COMMENT '吸收存款（银行间）(元)',
  `accrued_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '预提费用 (元)',
  `agent_trade_security` DECIMAL(20,4) DEFAULT NULL COMMENT '代理交易证券 (元)',
  `agent_underwrite_security` DECIMAL(20,4) DEFAULT NULL COMMENT '代理承销证券 (元)',
  `amortize_cost_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '摊余成本金融资产 (元)',
  `amortize_cost_finliab` DECIMAL(20,4) DEFAULT NULL COMMENT '摊余成本金融负债 (元)',
  `amortize_cost_ncfinasset` DECIMAL(20,4) DEFAULT NULL COMMENT '摊余成本非金融资产 (元)',
  `amortize_cost_ncfinliab` DECIMAL(20,4) DEFAULT NULL COMMENT '摊余成本非金融负债 (元)',
  `appoint_fvtpl_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融资产 (元)',
  `appoint_fvtpl_finliab` DECIMAL(20,4) DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融负债 (元)',
  `asset_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '资产余额 (元)',
  `asset_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他资产 (元)',
  `assign_cash_dividend` DECIMAL(20,4) DEFAULT NULL COMMENT '分配现金股利 (元)',
  `available_sale_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '可供出售金融资产 (元)',
  `bond_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '应付债券 (元)',
  `borrow_fund` DECIMAL(20,4) DEFAULT NULL COMMENT '借款资金 (元)',
  `buy_resale_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '买入返售金融资产 (元)',
  `consumptive_biological_asset` DECIMAL(24,4) DEFAULT NULL COMMENT '消耗性生物资产 (元)',
  `convert_diff` DECIMAL(20,4) DEFAULT NULL COMMENT '折算差额 (元)',
  `current_asset_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '流动资产余额 (元)',
  `current_asset_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他流动资产 (元)',
  `current_liab_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '流动负债余额 (元)',
  `defer_income_1year` DECIMAL(20,4) DEFAULT NULL COMMENT '一年内到期的递延收益 (元)',
  `derivative_financial_liabilities` DECIMAL(20,4) DEFAULT NULL COMMENT '衍生金融负债 (元)',
  `develop_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '开发支出 (元)',
  `div_holdsale_asset` DECIMAL(20,4) DEFAULT NULL COMMENT '持有待售资产（分拆）(元)',
  `div_holdsale_liab` DECIMAL(20,4) DEFAULT NULL COMMENT '持有待售负债（分拆）(元)',
  `equity_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '权益余额 (元)',
  `equity_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他权益 (元)',
  `export_refund_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '出口退税应收 (元)',
  `fee_commission_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '应付手续费及佣金 (元)',
  `fin_fund` DECIMAL(20,4) DEFAULT NULL COMMENT '金融资金 (元)',
  `fixed_asset_disposal` DECIMAL(20,4) DEFAULT NULL COMMENT '固定资产清理 (元)',
  `fvtoci_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产 (元)',
  `fvtoci_ncfinasset` DECIMAL(20,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入其他综合收益的非金融资产 (元)',
  `fvtpl_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融资产 (元)',
  `fvtpl_finliab` DECIMAL(20,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融负债 (元)',
  `general_risk_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '一般风险准备 (元)',
  `hold_maturity_invest` DECIMAL(20,4) DEFAULT NULL COMMENT '持有至到期投资 (元)',
  `holdsale_asset` DECIMAL(20,4) DEFAULT NULL COMMENT '持有待售资产 (元)',
  `holdsale_liab` DECIMAL(20,4) DEFAULT NULL COMMENT '持有待售负债 (元)',
  `insurance_contract_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '保险合同准备金 (元)',
  `interest_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '应付利息 (元)',
  `interest_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收利息 (元)',
  `internal_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '内部应付 (元)',
  `internal_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '内部应收 (元)',
  `lend_fund` DECIMAL(20,4) DEFAULT NULL COMMENT '拆出资金 (元)',
  `liab_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '负债余额 (元)',
  `liab_equity_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '负债及权益余额 (元)',
  `liab_equity_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他负债及权益 (元)',
  `liab_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他负债 (元)',
  `loan_advance` DECIMAL(20,4) DEFAULT NULL COMMENT '贷款及垫款 (元)',
  `loan_pbc` DECIMAL(20,4) DEFAULT NULL COMMENT '向中央银行借款 (元)',
  `long_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '长期应付款 (元)',
  `long_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '长期应收款 (元)',
  `long_staffsalary_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '长期应付职工薪酬 (元)',
  `parent_equity_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '母公司权益余额 (元)',
  `parent_equity_other` DECIMAL(20,4) DEFAULT NULL COMMENT '母公司其他权益 (元)',
  `perpetual_bond` DECIMAL(20,4) DEFAULT NULL COMMENT '永续债 (元)',
  `perpetual_bond_paybale` DECIMAL(20,4) DEFAULT NULL COMMENT '应付永续债 (元)',
  `predict_current_liab` DECIMAL(20,4) DEFAULT NULL COMMENT '预计流动负债 (元)',
  `preferred_shares` DECIMAL(20,4) DEFAULT NULL COMMENT '优先股 (元)',
  `preferred_shares_paybale` DECIMAL(20,4) DEFAULT NULL COMMENT '应付优先股 (元)',
  `premium_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收保费 (元)',
  `productive_biology_asset` DECIMAL(20,4) DEFAULT NULL COMMENT '生产性生物资产 (元)',
  `project_material` DECIMAL(20,4) DEFAULT NULL COMMENT '工程物资 (元)',
  `rc_reserve_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收再保险准备金 (元)',
  `reinsure_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '应付再保险款 (元)',
  `reinsure_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收再保险款 (元)',
  `sell_repo_finasset` DECIMAL(20,4) DEFAULT NULL COMMENT '卖出回购金融资产 (元)',
  `settle_excess_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '结算备付金 (元)',
  `short_bond_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '短期应付债券 (元)',
  `short_fin_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '短期融资应付 (元)',
  `special_payable` DECIMAL(20,4) DEFAULT NULL COMMENT '专项应付款 (元)',
  `subsidy_rece` DECIMAL(20,4) DEFAULT NULL COMMENT '应收补贴 (元)',
  `trade_finasset_notfvtpl` DECIMAL(20,4) DEFAULT NULL COMMENT '非以公允价值计量且其变动计入当期损益的交易性金融资产 (元)',
  `trade_finliab` DECIMAL(20,4) DEFAULT NULL COMMENT '交易性金融负债 (元)',
  `trade_finliab_notfvtpl` DECIMAL(20,4) DEFAULT NULL COMMENT '非以公允价值计量且其变动计入当期损益的交易性金融负债 (元)',
  `unconfirm_invest_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '未确认投资损失 (元)',
  `accept_deposit_interbank_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '吸收存款（银行间）同比 (%)',
  `accounts_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其中应付账款同比 (%)',
  `accounts_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其中应收帐款同比 (%)',
  `accrued_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预提费用同比 (%)',
  `advance_receivables_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预收款项同比 (%)',
  `agent_trade_security_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '代理交易证券同比 (%)',
  `agent_underwrite_security_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '代理承销证券同比 (%)',
  `amortize_cost_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '摊余成本金融资产同比 (%)',
  `amortize_cost_finliab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '摊余成本金融负债同比 (%)',
  `amortize_cost_ncfinasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '摊余成本非金融资产同比 (%)',
  `amortize_cost_ncfinliab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '摊余成本非金融负债同比 (%)',
  `appoint_fvtpl_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融资产同比 (%)',
  `appoint_fvtpl_finliab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '指定以公允价值计量且其变动计入当期损益的金融负债同比 (%)',
  `asset_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资产余额同比 (%)',
  `asset_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他资产同比 (%)',
  `assign_cash_dividend_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '分配现金股利同比 (%)',
  `available_sale_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '可供出售金融资产同比 (%)',
  `bond_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付债券同比 (%)',
  `borrow_fund_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '借款资金同比 (%)',
  `buy_resale_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '买入返售金融资产同比 (%)',
  `capital_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资本公积同比 (%)',
  `cip_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '在建工程同比 (%)',
  `consumptive_biological_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '消耗性生物资产同比 (%)',
  `contract_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '合同资产同比 (%)',
  `contract_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '合同负债同比 (%)',
  `convert_diff_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '折算差额同比 (%)',
  `creditor_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '债权投资同比 (%)',
  `current_asset_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '流动资产余额同比 (%)',
  `current_asset_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他流动资产同比 (%)',
  `current_liab_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '流动负债余额同比 (%)',
  `defer_income_1year_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '一年内到期的递延收益同比 (%)',
  `defer_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延收益同比 (%)',
  `defer_tax_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延所得税资产同比 (%)',
  `defer_tax_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '递延所得税负债同比 (%)',
  `derive_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '衍生金融资产同比 (%)',
  `derive_finliab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '衍生金融负债同比 (%)',
  `develop_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '开发支出同比 (%)',
  `div_holdsale_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持有待售资产（分拆）同比 (%)',
  `div_holdsale_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持有待售负债（分拆）同比 (%)',
  `dividend_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其中应付股利同比 (%)',
  `dividend_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其中应收股利同比 (%)',
  `equity_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '权益余额同比 (%)',
  `equity_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他权益同比 (%)',
  `export_refund_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '出口退税应收同比 (%)',
  `fee_commission_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付手续费及佣金同比 (%)',
  `fin_fund_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '金融资金同比 (%)',
  `finance_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收款项融资同比 (%)',
  `fixed_asset_disposal_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '固定资产清理同比 (%)',
  `fixed_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '固定资产同比 (%)',
  `fvtoci_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入其他综合收益的金融资产同比 (%)',
  `fvtoci_ncfinasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入其他综合收益的非金融资产同比 (%)',
  `fvtpl_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融资产同比 (%)',
  `fvtpl_finliab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '以公允价值计量且其变动计入当期损益的金融负债同比 (%)',
  `general_risk_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '一般风险准备同比 (%)',
  `goodwill_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '商誉同比 (%)',
  `hold_maturity_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持有至到期投资同比 (%)',
  `holdsale_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持有待售资产同比 (%)',
  `holdsale_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持有待售负债同比 (%)',
  `insurance_contract_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '保险合同准备金同比 (%)',
  `intangible_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '无形资产同比 (%)',
  `interest_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付利息同比 (%)',
  `interest_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收利息同比 (%)',
  `internal_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '内部应付同比 (%)',
  `internal_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '内部应收同比 (%)',
  `inventory_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '存货同比 (%)',
  `invest_realestate_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资性房地产同比 (%)',
  `lease_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '租赁负债同比 (%)',
  `lend_fund_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '拆出资金同比 (%)',
  `liab_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '负债余额同比 (%)',
  `liab_equity_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '负债及权益余额同比 (%)',
  `liab_equity_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他负债及权益同比 (%)',
  `liab_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他负债同比 (%)',
  `loan_advance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '贷款及垫款同比 (%)',
  `loan_pbc_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '向中央银行借款同比 (%)',
  `long_equity_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期股权投资同比 (%)',
  `long_loan_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期借款同比 (%)',
  `long_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期应付款同比 (%)',
  `long_prepaid_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期待摊费用同比 (%)',
  `long_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期应收款同比 (%)',
  `long_staffsalary_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '长期应付职工薪酬同比 (%)',
  `minority_equity_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '少数股东权益同比 (%)',
  `monetaryfunds_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '货币资金同比 (%)',
  `noncurrent_asset_1year_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '一年内到期的非流动资产同比 (%)',
  `noncurrent_asset_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非流动资产余额同比 (%)',
  `noncurrent_asset_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他非流动资产同比 (%)',
  `noncurrent_liab_1year_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '一年内到期的非流动负债同比 (%)',
  `noncurrent_liab_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非流动负债余额同比 (%)',
  `noncurrent_liab_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他非流动负债同比 (%)',
  `note_accounts_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付票据及应付账款同比 (%)',
  `note_accounts_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收票据及应收账款同比 (%)',
  `note_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其中应付票据同比 (%)',
  `note_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其中应收票据同比 (%)',
  `oil_gas_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '油气资产同比 (%)',
  `other_compre_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他综合收益同比 (%)',
  `other_creditor_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他债权投资同比 (%)',
  `other_current_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他流动资产同比 (%)',
  `other_equity_invest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他权益工具投资同比 (%)',
  `other_equity_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他权益（其他）同比 (%)',
  `other_equity_tool_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他权益工具同比 (%)',
  `other_noncurrent_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他非流动金融资产同比 (%)',
  `total_other_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他应付款合计同比 (%)',
  `total_other_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他应收款合计同比 (%)',
  `parent_equity_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '母公司权益余额同比 (%)',
  `parent_equity_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '母公司其他权益同比 (%)',
  `perpetual_bond_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '永续债同比 (%)',
  `perpetual_bond_paybale_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付永续债同比 (%)',
  `predict_current_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预计流动负债同比 (%)',
  `predict_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预计负债同比 (%)',
  `preferred_shares_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '优先股同比 (%)',
  `preferred_shares_paybale_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付优先股同比 (%)',
  `premium_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收保费同比 (%)',
  `prepayment_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '预付款项同比 (%)',
  `productive_biology_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '生产性生物资产同比 (%)',
  `project_material_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '工程物资同比 (%)',
  `rc_reserve_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收再保险准备金同比 (%)',
  `reinsure_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付再保险款同比 (%)',
  `reinsure_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收再保险款同比 (%)',
  `sell_repo_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '卖出回购金融资产同比 (%)',
  `settle_excess_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '结算备付金同比 (%)',
  `share_capital_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '实收资本 (或股本)同比 (%)',
  `short_bond_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '短期应付债券同比 (%)',
  `short_fin_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '短期融资应付同比 (%)',
  `short_loan_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '短期借款同比 (%)',
  `special_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '专项应付款同比 (%)',
  `special_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '专项储备同比 (%)',
  `staff_salary_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应付职工薪酬同比 (%)',
  `subsidy_rece_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应收补贴同比 (%)',
  `surplus_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '盈余公积同比 (%)',
  `tax_payable_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '应交税费同比 (%)',
  `total_assets_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资产总计同比 (%)',
  `total_current_assets_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '流动资产合计同比 (%)',
  `total_current_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '流动负债合计同比 (%)',
  `total_equity_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '股东权益合计同比 (%)',
  `total_liab_equity_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '负债和股东权益总计同比 (%)',
  `total_liabilities_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '负债合计同比 (%)',
  `total_noncurrent_assets_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非流动资产合计同比 (%)',
  `total_noncurrent_liab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非流动负债合计同比 (%)',
  `total_parent_equity_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '归属于母公司股东权益总计同比 (%)',
  `trade_finasset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '交易性金融资产同比 (%)',
  `trade_finasset_notfvtpl_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非以公允价值计量且其变动计入当期损益的交易性金融资产同比 (%)',
  `trade_finliab_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '交易性金融负债同比 (%)',
  `trade_finliab_notfvtpl_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非以公允价值计量且其变动计入当期损益的交易性金融负债同比 (%)',
  `treasury_shares_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '减库存股同比 (%)',
  `unassign_rprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '未分配利润同比 (%)',
  `unconfirm_invest_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '未确认投资损失同比 (%)',
  `userright_asset_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '使用权资产同比 (%)',

  -- ========== 其他字段 ==========
  `osopinion_type` VARCHAR(255) DEFAULT NULL COMMENT '其他审计意见类型',
  `listing_state` VARCHAR(255) DEFAULT NULL COMMENT '上市状态',

  -- ========== 系统字段 ==========
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',

  -- ========== 索引 ==========
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pmid` (`pmid`),
  INDEX `idx_stock_code` (`stock_code`),
  INDEX `idx_report_date` (`report_date`),
  INDEX `idx_stock_date` (`stock_code`, `report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='上市公司-资产负债表';
