CREATE TABLE `listed_income_statement` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `pmid` VARCHAR(32) NOT NULL COMMENT 'md5(stock_code+report_date)',
  `stock_code` VARCHAR(20) NOT NULL COMMENT '股票代码',
  `stock_name` VARCHAR(255) NOT NULL COMMENT '股票简称',
  `security_code` VARCHAR(20) DEFAULT NULL COMMENT '证券代码（不含交易所后缀）',
  `org_code` VARCHAR(30) DEFAULT NULL COMMENT '组织代码',
  `org_type` VARCHAR(255) DEFAULT NULL COMMENT '组织类型',
  `report_date` DATE NOT NULL COMMENT '报告日期',
  `report_type` VARCHAR(255) DEFAULT NULL COMMENT '报告类型',
  `report_date_name` VARCHAR(255) DEFAULT NULL COMMENT '报告日期名称',
  `security_type_code` VARCHAR(10) DEFAULT NULL COMMENT '证券类型代码',
  `notice_date` DATE DEFAULT NULL COMMENT '公告日期',
  `update_date` DATE DEFAULT NULL COMMENT '更新日期',
  `currency` VARCHAR(255) DEFAULT NULL COMMENT '货币单位',

  -- ========== 营业总收入 ==========
  `total_operate_income` DECIMAL(24,4) DEFAULT NULL COMMENT '营业总收入',
  `total_operate_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业总收入同比',
  `operate_income` DECIMAL(20,4) DEFAULT NULL COMMENT '营业收入',
  `operate_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业收入同比',
  `interest_income` DECIMAL(20,4) DEFAULT NULL COMMENT '利息收入',
  `interest_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '利息收入同比',
  `earned_premium` DECIMAL(20,4) DEFAULT NULL COMMENT '已赚保费',
  `earned_premium_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '已赚保费同比',
  `fee_commission_income` DECIMAL(20,4) DEFAULT NULL COMMENT '手续费及佣金收入',
  `fee_commission_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '手续费及佣金收入同比',
  `other_business_income` DECIMAL(20,4) DEFAULT NULL COMMENT '其他业务收入',
  `other_business_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他业务收入同比',
  `toi_other` DECIMAL(20,4) DEFAULT NULL COMMENT '营业总收入其他项',
  `toi_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业总收入其他项同比',

  -- ========== 营业总成本 ==========
  `total_operate_cost` DECIMAL(24,4) DEFAULT NULL COMMENT '营业总成本',
  `total_operate_cost_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业总成本同比',
  `operate_cost` DECIMAL(20,4) DEFAULT NULL COMMENT '营业成本',
  `operate_cost_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业成本同比',
  `interest_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '利息支出',
  `interest_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '利息支出同比',
  `fee_commission_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '手续费及佣金支出',
  `fee_commission_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '手续费及佣金支出同比',
  `research_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '研发费用',
  `research_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '研发费用同比',
  `surrender_value` DECIMAL(20,4) DEFAULT NULL COMMENT '退保金',
  `surrender_value_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '退保金同比',
  `net_compensate_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '净赔付支出',
  `net_compensate_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净赔付支出同比',
  `net_contract_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '净合同准备金',
  `net_contract_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净合同准备金同比',
  `policy_bonus_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '保单红利支出',
  `policy_bonus_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '保单红利支出同比',
  `reinsure_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '分保费用',
  `reinsure_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '分保费用同比',
  `other_business_cost` DECIMAL(20,4) DEFAULT NULL COMMENT '其他业务成本',
  `other_business_cost_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他业务成本同比',
  `operate_tax_add` DECIMAL(20,4) DEFAULT NULL COMMENT '营业税金及附加',
  `operate_tax_add_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业税金及附加同比',
  `sale_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '销售费用',
  `sale_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '销售费用同比',
  `manage_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '管理费用',
  `manage_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '管理费用同比',
  `me_research_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '管理费用中的研发费用',
  `me_research_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '管理费用中的研发费用同比',
  `finance_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '财务费用',
  `finance_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '财务费用同比',
  `fe_interest_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '财务费用中的利息支出',
  `fe_interest_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '财务费用中的利息支出同比',
  `fe_interest_income` DECIMAL(20,4) DEFAULT NULL COMMENT '财务费用中的利息收入',
  `fe_interest_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '财务费用中的利息收入同比',
  `asset_impairment_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '资产减值损失',
  `asset_impairment_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资产减值损失同比',
  `credit_impairment_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '信用减值损失',
  `credit_impairment_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '信用减值损失同比',
  `toc_other` DECIMAL(20,4) DEFAULT NULL COMMENT '营业总成本其他项',
  `toc_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业总成本其他项同比',

  -- ========== 营业利润 ==========
  `fairvalue_change_income` DECIMAL(20,4) DEFAULT NULL COMMENT '公允价值变动收益',
  `fairvalue_change_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '公允价值变动收益同比',
  `invest_income` DECIMAL(20,4) DEFAULT NULL COMMENT '投资收益',
  `invest_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '投资收益同比',
  `invest_joint_income` DECIMAL(20,4) DEFAULT NULL COMMENT '联营企业投资收益',
  `invest_joint_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '联营企业投资收益同比',
  `net_exposure_income` DECIMAL(20,4) DEFAULT NULL COMMENT '净敞口收益',
  `net_exposure_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净敞口收益同比',
  `exchange_income` DECIMAL(20,4) DEFAULT NULL COMMENT '汇兑收益',
  `exchange_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '汇兑收益同比',
  `asset_disposal_income` DECIMAL(20,4) DEFAULT NULL COMMENT '资产处置收益',
  `asset_disposal_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资产处置收益同比',
  `asset_impairment_income` DECIMAL(20,4) DEFAULT NULL COMMENT '资产减值收益',
  `asset_impairment_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '资产减值收益同比',
  `credit_impairment_income` DECIMAL(20,4) DEFAULT NULL COMMENT '信用减值收益',
  `credit_impairment_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '信用减值收益同比',
  `other_income` DECIMAL(20,4) DEFAULT NULL COMMENT '其他收益',
  `other_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他收益同比',
  `operate_profit_other` DECIMAL(20,4) DEFAULT NULL COMMENT '营业利润其他项',
  `operate_profit_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业利润其他项同比',
  `operate_profit_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '营业利润余额',
  `operate_profit_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业利润余额同比',
  `operate_profit` DECIMAL(20,4) DEFAULT NULL COMMENT '营业利润',
  `operate_profit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业利润同比',

  -- ========== 营业外收入和支出 ==========
  `nonbusiness_income` DECIMAL(20,4) DEFAULT NULL COMMENT '营业外收入',
  `nonbusiness_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业外收入同比',
  `noncurrent_disposal_income` DECIMAL(20,4) DEFAULT NULL COMMENT '非流动资产处置收益',
  `noncurrent_disposal_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非流动资产处置收益同比',
  `nonbusiness_expense` DECIMAL(20,4) DEFAULT NULL COMMENT '营业外支出',
  `nonbusiness_expense_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '营业外支出同比',
  `noncurrent_disposal_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '非流动资产处置损失',
  `noncurrent_disposal_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '非流动资产处置损失同比',
  `effect_tp_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他影响利润总额项',
  `effect_tp_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他影响利润总额项同比',
  `total_profit_balance` DECIMAL(24,4) DEFAULT NULL COMMENT '利润总额余额',
  `total_profit_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '利润总额余额同比',
  `total_profit` DECIMAL(24,4) DEFAULT NULL COMMENT '利润总额',
  `total_profit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '利润总额同比',

  -- ========== 净利润 ==========
  `income_tax` DECIMAL(20,4) DEFAULT NULL COMMENT '所得税费用',
  `income_tax_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '所得税费用同比',
  `effect_netprofit_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他影响净利润项',
  `effect_netprofit_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他影响净利润项同比',
  `effect_netprofit_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '净利润影响余额',
  `effect_netprofit_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净利润影响余额同比',
  `unconfirm_invest_loss` DECIMAL(20,4) DEFAULT NULL COMMENT '未确认投资损失',
  `unconfirm_invest_loss_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '未确认投资损失同比',
  `netprofit` DECIMAL(24,4) DEFAULT NULL COMMENT '净利润',
  `netprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净利润同比',
  `precombine_profit` DECIMAL(20,4) DEFAULT NULL COMMENT '合并前利润',
  `precombine_profit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '合并前利润同比',
  `continued_netprofit` DECIMAL(20,4) DEFAULT NULL COMMENT '持续经营净利润',
  `continued_netprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持续经营净利润同比',
  `discontinued_netprofit` DECIMAL(20,4) DEFAULT NULL COMMENT '终止经营净利润',
  `discontinued_netprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '终止经营净利润同比',
  `parent_netprofit` DECIMAL(24,4) DEFAULT NULL COMMENT '归母净利润',
  `parent_netprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '归母净利润同比',
  `minority_interest` DECIMAL(20,4) DEFAULT NULL COMMENT '少数股东损益',
  `minority_interest_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '少数股东损益同比',
  `deduct_parent_netprofit` DECIMAL(24,4) DEFAULT NULL COMMENT '扣非归母净利润',
  `deduct_parent_netprofit_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '扣非归母净利润同比',
  `netprofit_other` DECIMAL(20,4) DEFAULT NULL COMMENT '净利润其他项',
  `netprofit_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净利润其他项同比',
  `netprofit_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '净利润余额',
  `netprofit_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '净利润余额同比',

  -- ========== 每股收益 ==========
  `basic_eps` DECIMAL(15,4) DEFAULT NULL COMMENT '基本每股收益',
  `basic_eps_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '基本每股收益同比',
  `diluted_eps` DECIMAL(15,4) DEFAULT NULL COMMENT '稀释每股收益',
  `diluted_eps_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '稀释每股收益同比',

  -- ========== 其他综合收益 ==========
  `other_compre_income` DECIMAL(20,4) DEFAULT NULL COMMENT '其他综合收益',
  `other_compre_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他综合收益同比',
  `parent_oci` DECIMAL(20,4) DEFAULT NULL COMMENT '归母其他综合收益',
  `parent_oci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '归母其他综合收益同比',
  `minority_oci` DECIMAL(20,4) DEFAULT NULL COMMENT '少数股东其他综合收益',
  `minority_oci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '少数股东其他综合收益同比',
  `parent_oci_other` DECIMAL(20,4) DEFAULT NULL COMMENT '归母其他综合收益其他项',
  `parent_oci_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '归母其他综合收益其他项同比',
  `parent_oci_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '归母其他综合收益余额',
  `parent_oci_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '归母其他综合收益余额同比',
  `unable_oci` DECIMAL(20,4) DEFAULT NULL COMMENT '不可重分类其他综合收益',
  `unable_oci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '不可重分类其他综合收益同比',
  `creditrisk_fairvalue_change` DECIMAL(20,4) DEFAULT NULL COMMENT '信用风险公允价值变动',
  `creditrisk_fairvalue_change_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '信用风险公允价值变动同比',
  `otherright_fairvalue_change` DECIMAL(20,4) DEFAULT NULL COMMENT '其他权益工具公允价值变动',
  `otherright_fairvalue_change_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他权益工具公允价值变动同比',
  `setup_profit_change` DECIMAL(20,4) DEFAULT NULL COMMENT '设立利润变动',
  `setup_profit_change_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '设立利润变动同比',
  `rightlaw_unable_oci` DECIMAL(20,4) DEFAULT NULL COMMENT '权益法下不可重分类其他综合收益',
  `rightlaw_unable_oci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '权益法下不可重分类其他综合收益同比',
  `unable_oci_other` DECIMAL(20,4) DEFAULT NULL COMMENT '不可重分类其他综合收益其他项',
  `unable_oci_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '不可重分类其他综合收益其他项同比',
  `unable_oci_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '不可重分类其他综合收益余额',
  `unable_oci_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '不可重分类其他综合收益余额同比',
  `able_oci` DECIMAL(20,4) DEFAULT NULL COMMENT '可重分类其他综合收益',
  `able_oci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '可重分类其他综合收益同比',
  `rightlaw_able_oci` DECIMAL(20,4) DEFAULT NULL COMMENT '权益法下可重分类其他综合收益',
  `rightlaw_able_oci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '权益法下可重分类其他综合收益同比',
  `afa_fairvalue_change` DECIMAL(20,4) DEFAULT NULL COMMENT '可供出售金融资产公允价值变动',
  `afa_fairvalue_change_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '可供出售金融资产公允价值变动同比',
  `hmi_afa` DECIMAL(20,4) DEFAULT NULL COMMENT '持有至到期投资',
  `hmi_afa_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '持有至到期投资同比',
  `cashflow_hedge_valid` DECIMAL(20,4) DEFAULT NULL COMMENT '现金流套期保值有效部分',
  `cashflow_hedge_valid_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '现金流套期保值有效部分同比',
  `creditor_fairvalue_change` DECIMAL(20,4) DEFAULT NULL COMMENT '债权公允价值变动',
  `creditor_fairvalue_change_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '债权公允价值变动同比',
  `creditor_impairment_reserve` DECIMAL(20,4) DEFAULT NULL COMMENT '债权减值准备',
  `creditor_impairment_reserve_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '债权减值准备同比',
  `finance_oci_amt` DECIMAL(20,4) DEFAULT NULL COMMENT '财务其他综合收益金额',
  `finance_oci_amt_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '财务其他综合收益金额同比',
  `convert_diff` DECIMAL(20,4) DEFAULT NULL COMMENT '折算差额',
  `convert_diff_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '折算差额同比',
  `able_oci_other` DECIMAL(20,4) DEFAULT NULL COMMENT '可重分类其他综合收益其他项',
  `able_oci_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '可重分类其他综合收益其他项同比',
  `able_oci_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '可重分类其他综合收益余额',
  `able_oci_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '可重分类其他综合收益余额同比',
  `oci_other` DECIMAL(20,4) DEFAULT NULL COMMENT '其他综合收益其他项',
  `oci_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他综合收益其他项同比',
  `oci_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '其他综合收益余额',
  `oci_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '其他综合收益余额同比',

  -- ========== 综合收益 ==========
  `total_compre_income` DECIMAL(24,4) DEFAULT NULL COMMENT '综合收益总额',
  `total_compre_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '综合收益总额同比',
  `parent_tci` DECIMAL(20,4) DEFAULT NULL COMMENT '归母综合收益',
  `parent_tci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '归母综合收益同比',
  `minority_tci` DECIMAL(20,4) DEFAULT NULL COMMENT '少数股东综合收益',
  `minority_tci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '少数股东综合收益同比',
  `precombine_tci` DECIMAL(20,4) DEFAULT NULL COMMENT '合并前综合收益',
  `precombine_tci_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '合并前综合收益同比',
  `effect_tci_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '综合收益影响余额',
  `effect_tci_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '综合收益影响余额同比',
  `tci_other` DECIMAL(20,4) DEFAULT NULL COMMENT '综合收益其他项',
  `tci_other_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '综合收益其他项同比',
  `tci_balance` DECIMAL(20,4) DEFAULT NULL COMMENT '综合收益余额',
  `tci_balance_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '综合收益余额同比',
  `acf_end_income` DECIMAL(20,4) DEFAULT NULL COMMENT '会计期间末收入',
  `acf_end_income_yoy` DECIMAL(15,4) DEFAULT NULL COMMENT '会计期间末收入同比',

  -- ========== 审计意见 ==========
  `opinion_type` VARCHAR(255) DEFAULT NULL COMMENT '审计意见类型',

  -- ========== 系统字段 ==========
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',

  -- ========== 索引 ==========
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_pmid` (`pmid`),
  INDEX `idx_stock_code` (`stock_code`),
  INDEX `idx_report_date` (`report_date`),
  INDEX `idx_stock_date` (`stock_code`, `report_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='上市公司-利润表';