# -*- coding: UTF-8 -*-
"""
数据项定义
"""

from crawlo.items import Item, Field



class CoreFinancialIndicatorsItem(Item):
    """
     财务分析
     表名：listed_finance_and_taxation_report
    """
    pmid = Field()  # 主键，建议组合：secu_code + report_date

    # ========== 基础信息（按需求重命名）==========
    stock_code = Field()  # SECUCODE 股票代码
    stock_name = Field()  # SECURITY_NAME_ABBR 股票简称
    report_date = Field()  # REPORT_DATE 报告日期

    # ========== 每股指标（按需求重命名）==========
    basic_eps = Field()  # EPSJB 基本每股收益 (元)
    diluted_eps = Field()  # EPSXS 稀释每股收益 (元)
    non_gaap_eps = Field()  # EPSKCJB 扣非每股收益 (元)
    book_value_per_share = Field()  # BPS 每股净资产 (元)
    capital_reserve_per_share = Field()  # MGZBGJ 每股公积金 (元)
    undistributed_profit_per_share = Field()  # MGWFPLR 每股未分配利润 (元)
    operating_cash_flow_per_share = Field()  # MGJYXJJE 每股经营现金流 (元)

    # ========== 盈利能力（按需求重命名）==========
    total_operating_revenue = Field()  # TOTALOPERATEREVE 营业总收入 (元)
    gross_profit = Field()  # MLR 毛利润 (元)
    net_profit = Field()  # PARENTNETPROFIT 归属净利润 (元)
    non_gaap_net_profit = Field()  # KCFJCXSYJLR 扣非净利润 (元)

    roe_wa = Field()  # ROEJQ 净资产收益率 (加权)(%)
    roe_nwa = Field()  # ROEKCJQ 净资产收益率 (扣非加权)(%)
    roa_wa = Field()  # ZZCJLL 总资产收益率 (加权)(%)
    gross_margin = Field()  # XSMLL 毛利率 (%)
    net_margin = Field()  # XSJLL 净利率 (%)
    actual_tax_rate = Field()  # TAXRATE 实际税率 (%)

    # ========== 成长能力（按需求重命名）==========
    yoy_total_operating_revenue = Field()  # TOTALOPERATEREVETZ 营业总收入同比增长 (%)
    yoy_net_profit = Field()  # PARENTNETPROFITTZ 归属净利润同比增长 (%)
    yoy_non_gaap_net_profit = Field()  # KCFJCXSYJLRTZ 扣非净利润同比增长 (%)
    qoq_total_operating_revenue = Field()  # YYZSRGDHBZC      DJD_TOI_QOQ 营业总收入滚动环比增长 (%)
    qoq_net_profit = Field()  # DJD_DPNP_QOQ 归属净利润滚动环比增长 (%)
    qoq_non_gaap_net_profit = Field()  # DJD_DEDUCTDPNP_QOQ 扣非净利润滚动环比增长 (%)

    # ========== 收益质量（按需求重命名）==========
    advance_receipts_to_revenue = Field()  # YSZKYYSR 预收账款 / 营业收入 → 原数据为 None
    net_sales_cash_to_revenue = Field()  # XSJXLYYSR 销售净现金流 / 营业收入
    operating_cash_flow_to_revenue = Field()  # JYXJLYYSR 经营净现金流 / 营业收入

    # ========== 财务风险（按需求重命名）==========
    current_ratio = Field()  # LD 流动比率
    quick_ratio = Field()  # SD 速动比率
    cash_ratio = Field()  # XJLLB 现金流量比率
    asset_liability_ratio = Field()  # ZCFZL 资产负债率 (%)
    equity_coefficient = Field()  # QYCS 权益系数
    equity_ratio = Field()  # CQBL 产权比率

    # ========== 营运能力（按需求重命名）==========
    total_asset_turnover_days = Field()  # ZZCZZTS 总资产周转天数 (天)
    inventory_turnover_days = Field()  # CHZZTS 存货周转天数 (天)
    accounts_receivable_turnover_days = Field()  # YSZKZZTS 应收账款周转天数 (天)
    total_asset_turnover_times = Field()  # TOAZZL 总资产周转率 (次)
    inventory_turnover_times = Field()  # CHZZL 存货周转率 (次)
    accounts_receivable_turnover_times = Field()  # YSZKZZL 应收账款周转率 (次)

    # ========== ❗需求未包含字段（原样保留）==========
    security_code = Field()  # SECURITY_CODE 证券代码（纯数字）→ 需求无，保留
    org_code = Field()  # ORG_CODE 机构代码 → 需求无，保留
    org_type = Field()  # ORG_TYPE 机构类型 → 需求无，保留
    report_type = Field()  # REPORT_TYPE 报告类型（如“中报”）→ 需求无，保留
    report_date_name = Field()  # REPORT_DATE_NAME 报告期名称（如“2025中报”）→ 需求无，保留
    security_type_code = Field()  # SECURITY_TYPE_CODE 证券类型代码 → 需求无，保留
    notice_date = Field()  # NOTICE_DATE 公告日期 → 需求无，保留
    update_date = Field()  # UPDATE_DATE 更新日期 → 需求无，保留
    currency = Field()  # CURRENCY 货币单位（CNY）→ 需求无，保留
    report_year = Field()  # REPORT_YEAR 报告年份 → 需求无，保留
    epsjbtz = Field()  # EPSJBTZ 基本每股收益同比增长率
    bps_tz = Field()  # BPSTZ 每股净资产同比增长率
    mgzbgjtz = Field()  # MGZBGJTZ 每股资本公积同比增长率
    mgwfplrtz = Field()  # MGWFPLRTZ 每股未分配利润同比增长率
    mgjyxjjetz = Field()  # MGJYXJJETZ 每股经营现金流同比增长率
    roejqtz = Field()  # ROEJQTZ 净资产收益率同比增长率
    zzcjlltz = Field()  # ZZCJLLTZ 总资产收益率同比增长率
    roictz = Field()  # ROICTZ ROIC同比增长率
    xsml_l_tb = Field()  # XSMLL_TB 毛利率同比变动
    yyzsrgdhbzc = Field()  # YYZSRGDHBZC 营业收入/固定资产 ❗网页未展示
    netprofitrphbzc = Field()  # NETPROFITRPHBZC 净利润/固定资产 ❗网页未展示
    kfjlrgdhbzc = Field()  # KFJLRGDHBZC 扣非净利润/固定资产 ❗网页未展示
    prepaid_accounts_ratio = Field()  # PREPAID_ACCOUNTS_RATIO 预付账款占比 ❗网页未展示
    accounts_payable_tr = Field()  # ACCOUNTS_PAYABLE_TR 应付账款周转率 ❗网页未展示
    fixed_asset_tr = Field()  # FIXED_ASSET_TR 固定资产周转率 ❗网页未展示
    current_asset_tr = Field()  # CURRENT_ASSET_TR 流动资产周转率 ❗网页未展示
    prepaid_accounts_tdays = Field()  # PREPAID_ACCOUNTS_TDAYS 预付账款周转天数 ❗网页未展示
    payable_tdays = Field()  # PAYABLE_TDAYS 应付账款周转天数 ❗网页未展示
    operate_cycle = Field()  # OPERATE_CYCLE 营运周期 ❗网页未展示
    guard_speed_ratio = Field()  # GUARD_SPEED_RATIO 保守速动比率 ❗网页未展示
    interest_coverage_ratio = Field()  # INTEREST_COVERAGE_RATIO 利息保障倍数 ❗网页未展示
    ca_ta = Field()  # CA_TA 流动资产/总资产 ❗网页未展示
    nca_ta = Field()  # NCA_TA 非流动资产/总资产 ❗网页未展示
    liquidation_ratio = Field()  # LIQUIDATION_RATIO 清算比率 ❗网页未展示
    interest_debt_ratio = Field()  # INTEREST_DEBT_RATIO 利息债务比 ❗网页未展示
    fc_liabilities = Field()  # FC_LIABILITIES 金融负债占比 ❗网页未展示
    liability = Field()  # LIABILITY 总负债 ❗网页未展示
    fcff_forward = Field()  # FCFF_FORWARD 前瞻自由现金流 ❗网页未展示
    fcff_back = Field()  # FCFF_BACK 回顾自由现金流 ❗网页未展示
    ss_oi = Field()  # SS_OI 销售费用/营业收入 ❗网页未展示
    ss_ta = Field()  # SS_TA 销售费用/总资产 ❗网页未展示
    nco_op = Field()  # NCO_OP 净经营资产/营业收入 ❗网页未展示
    nco_netprofit = Field()  # NCO_NETPROFIT 净经营资产/净利润 ❗网页未展示
    nco_fixed = Field()  # NCO_FIXED 净经营资产/固定资产 ❗网页未展示
    roic = Field()  # ROIC 投资资本回报率 ❗网页未直接展示
    djd_toi_yoy = Field()  # DJD_TOI_YOY 营业总收入同比增速（单季度）
    djd_dpnp_yoy = Field()  # DJD_DPNP_YOY 归属净利润同比增速（单季度）
    djd_deductdpnp_yoy = Field()  # DJD_DEDUCTDPNP_YOY 扣非净利润同比增速（单季度）
    per_toi = Field()  # PER_TOI 市销率（TTM）
    per_oi = Field()  # PER_OI 市销率（报告期）
    per_ebit = Field()  # PER_EBIT 市盈率（EBIT）
    zcfzltz = Field()  # ZCFZLTZ 资产负债率同比变动


class BalanceSheetItem(Item):
    """
    资产负债表
    表名：listed_balance_sheet_of_companies
    """
    pmid = Field()  # 主键，建议组合：secu_code + report_date
    # ========== 需求字段 ==========
    stock_code = Field()  # SECUCODE 股票代码
    stock_name = Field()  # SECURITY_NAME_ABBR 股票简称
    report_date = Field()  # REPORT_DATE 报告日期
    monetary_funds = Field()  # MONETARYFUNDS 货币资金 (元)
    trading_financial_assets = Field()  # TRADE_FINASSET 交易性金融资产 (元)
    trade_finasset_notfvtpl = Field()  # TRADE_FINASSET_NOTFVTPL 非以公允价值计量且其变动计入当期损益的交易性金融资产 (元)
    derivative_financial_assets = Field()  # DERIVE_FINASSET 衍生金融资产 (元)
    note_accounts_rece = Field()  # NOTE_ACCOUNTS_RECE 应收票据及应收账款 (元)
    notes_receivable = Field()  # NOTE_RECE 其中应收票据 (元)
    accounts_rece = Field()  # ACCOUNTS_RECE 其中应收帐款 (元)
    finance_rece = Field()  # FINANCE_RECE 应收款项融资 (元)
    prepaid_items = Field()  # PREPAYMENT 预付款项 (元)
    total_other_receivables = Field()  # TOTAL_OTHER_RECE 其他应收款合计 (元)
    receivable_dividends = Field()  # DIVIDEND_RECE 其中应收股利 (元)
    inventory = Field()  # INVENTORY 存货 (元)
    contract_assets = Field()  # CONTRACT_ASSET 合同资产 (元)
    other_current_assets = Field()  # OTHER_CURRENT_ASSET 其他流动资产 (元)
    total_current_assets = Field()  # TOTAL_CURRENT_ASSETS 流动资产合计 (元)
    other_noncurrent_finasset = Field()  # OTHER_NONCURRENT_FINASSET 其他非流动金融资产 (元)
    long_term_equity_investment = Field()  # LONG_EQUITY_INVEST 长期股权投资 (元)
    debt_investment = Field()  # CREDITOR_INVEST 债权投资 (元)
    other_equity_invest = Field()  # OTHER_EQUITY_INVEST 其他权益工具投资 (元)
    investment_property = Field()  # INVEST_REALESTATE 投资性房地产 (元)
    right_of_use_asset = Field()  # USERIGHT_ASSET 使用权资产 (元)
    fixed_assets = Field()  # FIXED_ASSET 固定资产 (元)
    construction_in_progress = Field()  # CIP 在建工程 (元)
    intangible_assets = Field()  # INTANGIBLE_ASSET 无形资产 (元)
    long_term_prepaid_expenses = Field()  # LONG_PREPAID_EXPENSE 长期待摊费用 (元)
    goodwill = Field()  # GOODWILL 商誉 (元)
    deferred_tax_assets = Field()  # DEFER_TAX_ASSET 递延所得税资产 (元)
    other_non_current_assets = Field()  # NONCURRENT_ASSET_OTHER 其他非流动资产 (元)
    total_non_current_assets = Field()  # TOTAL_NONCURRENT_ASSETS 非流动资产合计 (元)
    total_assets = Field()  # TOTAL_ASSETS 资产总计 (元)
    short_term_loans = Field()  # SHORT_LOAN 短期借款 (元)
    note_accounts_payable = Field()  # NOTE_ACCOUNTS_PAYABLE 应付票据及应付账款 (元)
    notes_payable = Field()  # NOTE_PAYABLE 其中应付票据 (元)
    accounts_payable = Field()  # ACCOUNTS_PAYABLE 其中应付账款 (元)
    advance_from_customers = Field()  # ADVANCE_RECEIVABLES 预收款项 (元)
    contract_liabilities = Field()  # CONTRACT_LIAB 合同负债 (元)
    employee_compensation = Field()  # STAFF_SALARY_PAYABLE 应付职工薪酬 (元)
    taxes_payable = Field()  # TAX_PAYABLE 应交税费 (元)
    total_other_payables = Field()  # TOTAL_OTHER_PAYABLE 其他应付款合计 (元)
    dividends_payable = Field()  # DIVIDEND_PAYABLE 其中应付股利 (元)
    noncurrent_liab_1year = Field()  # NONCURRENT_LIAB_1YEAR 一年内到期的非流动负债 (元)
    other_current_liabilities = Field()  # CURRENT_LIAB_OTHER 其他流动负债 (元)
    total_current_liabilities = Field()  # TOTAL_CURRENT_LIAB 流动负债合计 (元)
    lease_liabilities_long_term = Field()  # LEASE_LIAB 租赁负债 (元)
    long_term_loans = Field()  # LONG_LOAN 长期借款 (元)
    lease_liabilities = Field()  # LEASE_LIAB 租赁负债 (元)
    estimated_liabilities = Field()  # PREDICT_LIAB 预计负债 (元)
    deferred_revenue = Field()  # DEFER_INCOME 递延收益 (元)
    defer_tax_liab = Field()  # DEFER_TAX_LIAB 递延所得税负债 (元)
    total_noncurrent_liab = Field()  # TOTAL_NONCURRENT_LIAB 非流动负债合计 (元)
    total_liabilities = Field()  # TOTAL_LIABILITIES 负债合计 (元)
    paid_in_capital = Field()  # SHARE_CAPITAL 实收资本 (或股本) (元)
    other_equity_instruments = Field()  # OTHER_EQUITY_TOOL 其他权益工具 (元)
    capital_reserve = Field()  # CAPITAL_RESERVE 资本公积 (元)
    treasury_stock = Field()  # TREASURY_SHARES 减库存股 (元)
    other_compre_income = Field()  # OTHER_COMPRE_INCOME 其他综合收益 (元)
    dedicated_reserves = Field()  # SPECIAL_RESERVE 专项储备 (元)
    surplus_reserve = Field()  # SURPLUS_RESERVE 盈余公积 (元)
    undistributed_profit = Field()  # UNASSIGN_RPOFIT 未分配利润 (元)
    total_parent_equity = Field()  # TOTAL_PARENT_EQUITY 归属于母公司股东权益总计 (元)
    minority_interest = Field()  # MINORITY_EQUITY 少数股东权益 (元)
    total_equity = Field()  # TOTAL_EQUITY 股东权益合计 (元)
    total_liabilities_and_equity = Field()  # TOTAL_LIAB_EQUITY 负债和股东权益总计 (元)
    audit_opinion_domestic = Field()  # OPINION_TYPE 审计意见 (境内)
    # ========== 额外的字段 ==========
    security_code = Field()  # SECURITY_CODE 证券代码
    org_code = Field()  # ORG_CODE 机构代码
    org_type = Field()  # ORG_TYPE 机构类型
    report_type = Field()  # REPORT_TYPE 报告类型
    report_date_name = Field()  # REPORT_DATE_NAME 报告日期名称（如 2025中报）
    security_type_code = Field()  # SECURITY_TYPE_CODE 证券类型代码
    notice_date = Field()  # NOTICE_DATE 公告日期
    update_date = Field()  # UPDATE_DATE 更新日期
    currency = Field()  # CURRENCY 货币单位
    accept_deposit_interbank = Field()  # ACCEPT_DEPOSIT_INTERBANK 吸收存款（银行间）(元)
    accrued_expense = Field()  # ACCRUED_EXPENSE 预提费用 (元)
    agent_trade_security = Field()  # AGENT_TRADE_SECURITY 代理交易证券 (元)
    agent_underwrite_security = Field()  # AGENT_UNDERWRITE_SECURITY 代理承销证券 (元)
    amortize_cost_finasset = Field()  # AMORTIZE_COST_FINASSET 摊余成本金融资产 (元)
    amortize_cost_finliab = Field()  # AMORTIZE_COST_FINLIAB 摊余成本金融负债 (元)
    amortize_cost_ncfinasset = Field()  # AMORTIZE_COST_NCFINASSET 摊余成本非金融资产 (元)
    amortize_cost_ncfinliab = Field()  # AMORTIZE_COST_NCFINLIAB 摊余成本非金融负债 (元)
    appoint_fvtpl_finasset = Field()  # APPOINT_FVTPL_FINASSET 指定以公允价值计量且其变动计入当期损益的金融资产 (元)
    appoint_fvtpl_finliab = Field()  # APPOINT_FVTPL_FINLIAB 指定以公允价值计量且其变动计入当期损益的金融负债 (元)
    asset_balance = Field()  # ASSET_BALANCE 资产余额 (元)
    asset_other = Field()  # ASSET_OTHER 其他资产 (元)
    assign_cash_dividend = Field()  # ASSIGN_CASH_DIVIDEND 分配现金股利 (元)
    available_sale_finasset = Field()  # AVAILABLE_SALE_FINASSET 可供出售金融资产 (元)
    bond_payable = Field()  # BOND_PAYABLE 应付债券 (元)
    borrow_fund = Field()  # BORROW_FUND 借款资金 (元)
    buy_resale_finasset = Field()  # BUY_RESALE_FINASSET 买入返售金融资产 (元)
    consumptive_biological_asset = Field()  # CONSUMPTIVE_BIOLOGICAL_ASSET 消耗性生物资产 (元)
    convert_diff = Field()  # CONVERT_DIFF 折算差额 (元)
    current_asset_balance = Field()  # CURRENT_ASSET_BALANCE 流动资产余额 (元)
    current_asset_other = Field()  # CURRENT_ASSET_OTHER 其他流动资产 (元)
    current_liab_balance = Field()  # CURRENT_LIAB_BALANCE 流动负债余额 (元)
    defer_income_1year = Field()  # DEFER_INCOME_1YEAR 一年内到期的递延收益 (元)
    derivative_financial_liabilities = Field()  # DERIVE_FINLIAB 衍生金融负债 (元)
    develop_expense = Field()  # DEVELOP_EXPENSE 开发支出 (元)
    div_holdsale_asset = Field()  # DIV_HOLDSALE_ASSET 持有待售资产（分拆）(元)
    div_holdsale_liab = Field()  # DIV_HOLDSALE_LIAB 持有待售负债（分拆）(元)
    equity_balance = Field()  # EQUITY_BALANCE 权益余额 (元)
    equity_other = Field()  # EQUITY_OTHER 其他权益 (元)
    export_refund_rece = Field()  # EXPORT_REFUND_RECE 出口退税应收 (元)
    fee_commission_payable = Field()  # FEE_COMMISSION_PAYABLE 应付手续费及佣金 (元)
    fin_fund = Field()  # FIN_FUND 金融资金 (元)
    fixed_asset_disposal = Field()  # FIXED_ASSET_DISPOSAL 固定资产清理 (元)
    fvtoci_finasset = Field()  # FVTOCI_FINASSET 以公允价值计量且其变动计入其他综合收益的金融资产 (元)
    fvtoci_ncfinasset = Field()  # FVTOCI_NCFINASSET 以公允价值计量且其变动计入其他综合收益的非金融资产 (元)
    fvtpl_finasset = Field()  # FVTPL_FINASSET 以公允价值计量且其变动计入当期损益的金融资产 (元)
    fvtpl_finliab = Field()  # FVTPL_FINLIAB 以公允价值计量且其变动计入当期损益的金融负债 (元)
    general_risk_reserve = Field()  # GENERAL_RISK_RESERVE 一般风险准备 (元)
    hold_maturity_invest = Field()  # HOLD_MATURITY_INVEST 持有至到期投资 (元)
    holdsale_asset = Field()  # HOLDSALE_ASSET 持有待售资产 (元)
    holdsale_liab = Field()  # HOLDSALE_LIAB 持有待售负债 (元)
    insurance_contract_reserve = Field()  # INSURANCE_CONTRACT_RESERVE 保险合同准备金 (元)
    interest_payable = Field()  # INTEREST_PAYABLE 应付利息 (元)
    interest_rece = Field()  # INTEREST_RECE 应收利息 (元)
    internal_payable = Field()  # INTERNAL_PAYABLE 内部应付 (元)
    internal_rece = Field()  # INTERNAL_RECE 内部应收 (元)
    lend_fund = Field()  # LEND_FUND 拆出资金 (元)
    liab_balance = Field()  # LIAB_BALANCE 负债余额 (元)
    liab_equity_balance = Field()  # LIAB_EQUITY_BALANCE 负债及权益余额 (元)
    liab_equity_other = Field()  # LIAB_EQUITY_OTHER 其他负债及权益 (元)
    liab_other = Field()  # LIAB_OTHER 其他负债 (元)
    loan_advance = Field()  # LOAN_ADVANCE 贷款及垫款 (元)
    loan_pbc = Field()  # LOAN_PBC 向中央银行借款 (元)
    long_payable = Field()  # LONG_PAYABLE 长期应付款 (元)
    long_rece = Field()  # LONG_RECE 长期应收款 (元)
    long_staffsalary_payable = Field()  # LONG_STAFFSALARY_PAYABLE 长期应付职工薪酬 (元)
    parent_equity_balance = Field()  # PARENT_EQUITY_BALANCE 母公司权益余额 (元)
    parent_equity_other = Field()  # PARENT_EQUITY_OTHER 母公司其他权益 (元)
    perpetual_bond = Field()  # PERPETUAL_BOND 永续债 (元)
    perpetual_bond_paybale = Field()  # PERPETUAL_BOND_PAYBALE 应付永续债 (元)
    predict_current_liab = Field()  # PREDICT_CURRENT_LIAB 预计流动负债 (元)
    preferred_shares = Field()  # PREFERRED_SHARES 优先股 (元)
    preferred_shares_paybale = Field()  # PREFERRED_SHARES_PAYBALE 应付优先股 (元)
    premium_rece = Field()  # PREMIUM_RECE 应收保费 (元)
    productive_biology_asset = Field()  # PRODUCTIVE_BIOLOGY_ASSET 生产性生物资产 (元)
    project_material = Field()  # PROJECT_MATERIAL 工程物资 (元)
    rc_reserve_rece = Field()  # RC_RESERVE_RECE 应收再保险准备金 (元)
    reinsure_payable = Field()  # REINSURE_PAYABLE 应付再保险款 (元)
    reinsure_rece = Field()  # REINSURE_RECE 应收再保险款 (元)
    sell_repo_finasset = Field()  # SELL_REPO_FINASSET 卖出回购金融资产 (元)
    settle_excess_reserve = Field()  # SETTLE_EXCESS_RESERVE 结算备付金 (元)
    short_bond_payable = Field()  # SHORT_BOND_PAYABLE 短期应付债券 (元)
    short_fin_payable = Field()  # SHORT_FIN_PAYABLE 短期融资应付 (元)
    special_payable = Field()  # SPECIAL_PAYABLE 专项应付款 (元)
    subsidy_rece = Field()  # SUBSIDY_RECE 应收补贴 (元)
    trade_finliab = Field()  # TRADE_FINLIAB 交易性金融负债 (元)
    trade_finliab_notfvtpl = Field()  # TRADE_FINLIAB_NOTFVTPL 非以公允价值计量且其变动计入当期损益的交易性金融负债 (元)
    unconfirm_invest_loss = Field()  # UNCONFIRM_INVEST_LOSS 未确认投资损失 (元)
    accept_deposit_interbank_yoy = Field()  # ACCEPT_DEPOSIT_INTERBANK_YOY 吸收存款（银行间）同比 (%)
    accounts_payable_yoy = Field()  # ACCOUNTS_PAYABLE_YOY 其中应付账款同比 (%)
    accounts_rece_yoy = Field()  # ACCOUNTS_RECE_YOY 其中应收帐款同比 (%)
    accrued_expense_yoy = Field()  # ACCRUED_EXPENSE_YOY 预提费用同比 (%)
    advance_receivables_yoy = Field()  # ADVANCE_RECEIVABLES_YOY 预收款项同比 (%)
    agent_trade_security_yoy = Field()  # AGENT_TRADE_SECURITY_YOY 代理交易证券同比 (%)
    agent_underwrite_security_yoy = Field()  # AGENT_UNDERWRITE_SECURITY_YOY 代理承销证券同比 (%)
    amortize_cost_finasset_yoy = Field()  # AMORTIZE_COST_FINASSET_YOY 摊余成本金融资产同比 (%)
    amortize_cost_finliab_yoy = Field()  # AMORTIZE_COST_FINLIAB_YOY 摊余成本金融负债同比 (%)
    amortize_cost_ncfinasset_yoy = Field()  # AMORTIZE_COST_NCFINASSET_YOY 摊余成本非金融资产同比 (%)
    amortize_cost_ncfinliab_yoy = Field()  # AMORTIZE_COST_NCFINLIAB_YOY 摊余成本非金融负债同比 (%)
    appoint_fvtpl_finasset_yoy = Field()  # APPOINT_FVTPL_FINASSET_YOY 指定以公允价值计量且其变动计入当期损益的金融资产同比 (%)
    appoint_fvtpl_finliab_yoy = Field()  # APPOINT_FVTPL_FINLIAB_YOY 指定以公允价值计量且其变动计入当期损益的金融负债同比 (%)
    asset_balance_yoy = Field()  # ASSET_BALANCE_YOY 资产余额同比 (%)
    asset_other_yoy = Field()  # ASSET_OTHER_YOY 其他资产同比 (%)
    assign_cash_dividend_yoy = Field()  # ASSIGN_CASH_DIVIDEND_YOY 分配现金股利同比 (%)
    available_sale_finasset_yoy = Field()  # AVAILABLE_SALE_FINASSET_YOY 可供出售金融资产同比 (%)
    bond_payable_yoy = Field()  # BOND_PAYABLE_YOY 应付债券同比 (%)
    borrow_fund_yoy = Field()  # BORROW_FUND_YOY 借款资金同比 (%)
    buy_resale_finasset_yoy = Field()  # BUY_RESALE_FINASSET_YOY 买入返售金融资产同比 (%)
    capital_reserve_yoy = Field()  # CAPITAL_RESERVE_YOY 资本公积同比 (%)
    cip_yoy = Field()  # CIP_YOY 在建工程同比 (%)
    consumptive_biological_asset_yoy = Field()  # CONSUMPTIVE_BIOLOGICAL_ASSET_YOY 消耗性生物资产同比 (%)
    contract_asset_yoy = Field()  # CONTRACT_ASSET_YOY 合同资产同比 (%)
    contract_liab_yoy = Field()  # CONTRACT_LIAB_YOY 合同负债同比 (%)
    convert_diff_yoy = Field()  # CONVERT_DIFF_YOY 折算差额同比 (%)
    creditor_invest_yoy = Field()  # CREDITOR_INVEST_YOY 债权投资同比 (%)
    current_asset_balance_yoy = Field()  # CURRENT_ASSET_BALANCE_YOY 流动资产余额同比 (%)
    current_asset_other_yoy = Field()  # CURRENT_ASSET_OTHER_YOY 其他流动资产同比 (%)
    current_liab_balance_yoy = Field()  # CURRENT_LIAB_BALANCE_YOY 流动负债余额同比 (%)
    defer_income_1year_yoy = Field()  # DEFER_INCOME_1YEAR_YOY 一年内到期的递延收益同比 (%)
    defer_income_yoy = Field()  # DEFER_INCOME_YOY 递延收益同比 (%)
    defer_tax_asset_yoy = Field()  # DEFER_TAX_ASSET_YOY 递延所得税资产同比 (%)
    defer_tax_liab_yoy = Field()  # DEFER_TAX_LIAB_YOY 递延所得税负债同比 (%)
    derive_finasset_yoy = Field()  # DERIVE_FINASSET_YOY 衍生金融资产同比 (%)
    derive_finliab_yoy = Field()  # DERIVE_FINLIAB_YOY 衍生金融负债同比 (%)
    develop_expense_yoy = Field()  # DEVELOP_EXPENSE_YOY 开发支出同比 (%)
    div_holdsale_asset_yoy = Field()  # DIV_HOLDSALE_ASSET_YOY 持有待售资产（分拆）同比 (%)
    div_holdsale_liab_yoy = Field()  # DIV_HOLDSALE_LIAB_YOY 持有待售负债（分拆）同比 (%)
    dividend_payable_yoy = Field()  # DIVIDEND_PAYABLE_YOY 其中应付股利同比 (%)
    dividend_rece_yoy = Field()  # DIVIDEND_RECE_YOY 其中应收股利同比 (%)
    equity_balance_yoy = Field()  # EQUITY_BALANCE_YOY 权益余额同比 (%)
    equity_other_yoy = Field()  # EQUITY_OTHER_YOY 其他权益同比 (%)
    export_refund_rece_yoy = Field()  # EXPORT_REFUND_RECE_YOY 出口退税应收同比 (%)
    fee_commission_payable_yoy = Field()  # FEE_COMMISSION_PAYABLE_YOY 应付手续费及佣金同比 (%)
    fin_fund_yoy = Field()  # FIN_FUND_YOY 金融资金同比 (%)
    finance_rece_yoy = Field()  # FINANCE_RECE_YOY 应收款项融资同比 (%)
    fixed_asset_disposal_yoy = Field()  # FIXED_ASSET_DISPOSAL_YOY 固定资产清理同比 (%)
    fixed_asset_yoy = Field()  # FIXED_ASSET_YOY 固定资产同比 (%)
    fvtoci_finasset_yoy = Field()  # FVTOCI_FINASSET_YOY 以公允价值计量且其变动计入其他综合收益的金融资产同比 (%)
    fvtoci_ncfinasset_yoy = Field()  # FVTOCI_NCFINASSET_YOY 以公允价值计量且其变动计入其他综合收益的非金融资产同比 (%)
    fvtpl_finasset_yoy = Field()  # FVTPL_FINASSET_YOY 以公允价值计量且其变动计入当期损益的金融资产同比 (%)
    fvtpl_finliab_yoy = Field()  # FVTPL_FINLIAB_YOY 以公允价值计量且其变动计入当期损益的金融负债同比 (%)
    general_risk_reserve_yoy = Field()  # GENERAL_RISK_RESERVE_YOY 一般风险准备同比 (%)
    goodwill_yoy = Field()  # GOODWILL_YOY 商誉同比 (%)
    hold_maturity_invest_yoy = Field()  # HOLD_MATURITY_INVEST_YOY 持有至到期投资同比 (%)
    holdsale_asset_yoy = Field()  # HOLDSALE_ASSET_YOY 持有待售资产同比 (%)
    holdsale_liab_yoy = Field()  # HOLDSALE_LIAB_YOY 持有待售负债同比 (%)
    insurance_contract_reserve_yoy = Field()  # INSURANCE_CONTRACT_RESERVE_YOY 保险合同准备金同比 (%)
    intangible_asset_yoy = Field()  # INTANGIBLE_ASSET_YOY 无形资产同比 (%)
    interest_payable_yoy = Field()  # INTEREST_PAYABLE_YOY 应付利息同比 (%)
    interest_rece_yoy = Field()  # INTEREST_RECE_YOY 应收利息同比 (%)
    internal_payable_yoy = Field()  # INTERNAL_PAYABLE_YOY 内部应付同比 (%)
    internal_rece_yoy = Field()  # INTERNAL_RECE_YOY 内部应收同比 (%)
    inventory_yoy = Field()  # INVENTORY_YOY 存货同比 (%)
    invest_realestate_yoy = Field()  # INVEST_REALESTATE_YOY 投资性房地产同比 (%)
    lease_liab_yoy = Field()  # LEASE_LIAB_YOY 租赁负债同比 (%)
    lend_fund_yoy = Field()  # LEND_FUND_YOY 拆出资金同比 (%)
    liab_balance_yoy = Field()  # LIAB_BALANCE_YOY 负债余额同比 (%)
    liab_equity_balance_yoy = Field()  # LIAB_EQUITY_BALANCE_YOY 负债及权益余额同比 (%)
    liab_equity_other_yoy = Field()  # LIAB_EQUITY_OTHER_YOY 其他负债及权益同比 (%)
    liab_other_yoy = Field()  # LIAB_OTHER_YOY 其他负债同比 (%)
    loan_advance_yoy = Field()  # LOAN_ADVANCE_YOY 贷款及垫款同比 (%)
    loan_pbc_yoy = Field()  # LOAN_PBC_YOY 向中央银行借款同比 (%)
    long_equity_invest_yoy = Field()  # LONG_EQUITY_INVEST_YOY 长期股权投资同比 (%)
    long_loan_yoy = Field()  # LONG_LOAN_YOY 长期借款同比 (%)
    long_payable_yoy = Field()  # LONG_PAYABLE_YOY 长期应付款同比 (%)
    long_prepaid_expense_yoy = Field()  # LONG_PREPAID_EXPENSE_YOY 长期待摊费用同比 (%)
    long_rece_yoy = Field()  # LONG_RECE_YOY 长期应收款同比 (%)
    long_staffsalary_payable_yoy = Field()  # LONG_STAFFSALARY_PAYABLE_YOY 长期应付职工薪酬同比 (%)
    minority_equity_yoy = Field()  # MINORITY_EQUITY_YOY 少数股东权益同比 (%)
    monetaryfunds_yoy = Field()  # MONETARYFUNDS_YOY 货币资金同比 (%)
    noncurrent_asset_1year_yoy = Field()  # NONCURRENT_ASSET_1YEAR_YOY 一年内到期的非流动资产同比 (%)
    noncurrent_asset_balance_yoy = Field()  # NONCURRENT_ASSET_BALANCE_YOY 非流动资产余额同比 (%)
    noncurrent_asset_other_yoy = Field()  # NONCURRENT_ASSET_OTHER_YOY 其他非流动资产同比 (%)
    noncurrent_liab_1year_yoy = Field()  # NONCURRENT_LIAB_1YEAR_YOY 一年内到期的非流动负债同比 (%)
    noncurrent_liab_balance_yoy = Field()  # NONCURRENT_LIAB_BALANCE_YOY 非流动负债余额同比 (%)
    noncurrent_liab_other_yoy = Field()  # NONCURRENT_LIAB_OTHER_YOY 其他非流动负债同比 (%)
    note_accounts_payable_yoy = Field()  # NOTE_ACCOUNTS_PAYABLE_YOY 应付票据及应付账款同比 (%)
    note_accounts_rece_yoy = Field()  # NOTE_ACCOUNTS_RECE_YOY 应收票据及应收账款同比 (%)
    note_payable_yoy = Field()  # NOTE_PAYABLE_YOY 其中应付票据同比 (%)
    note_rece_yoy = Field()  # NOTE_RECE_YOY 其中应收票据同比 (%)
    oil_gas_asset_yoy = Field()  # OIL_GAS_ASSET_YOY 油气资产同比 (%)
    other_compre_income_yoy = Field()  # OTHER_COMPRE_INCOME_YOY 其他综合收益同比 (%)
    other_creditor_invest_yoy = Field()  # OTHER_CREDITOR_INVEST_YOY 其他债权投资同比 (%)
    other_current_asset_yoy = Field()  # OTHER_CURRENT_ASSET_YOY 其他流动资产同比 (%)
    other_equity_invest_yoy = Field()  # OTHER_EQUITY_INVEST_YOY 其他权益工具投资同比 (%)
    other_equity_other_yoy = Field()  # OTHER_EQUITY_OTHER_YOY 其他权益（其他）同比 (%)
    other_equity_tool_yoy = Field()  # OTHER_EQUITY_TOOL_YOY 其他权益工具同比 (%)
    other_noncurrent_finasset_yoy = Field()  # OTHER_NONCURRENT_FINASSET_YOY 其他非流动金融资产同比 (%)
    total_other_payable_yoy = Field()  # TOTAL_OTHER_PAYABLE_YOY 其他应付款合计同比 (%)
    total_other_rece_yoy = Field()  # TOTAL_OTHER_RECE_YOY 其他应收款合计同比 (%)
    parent_equity_balance_yoy = Field()  # PARENT_EQUITY_BALANCE_YOY 母公司权益余额同比 (%)
    parent_equity_other_yoy = Field()  # PARENT_EQUITY_OTHER_YOY 母公司其他权益同比 (%)
    perpetual_bond_yoy = Field()  # PERPETUAL_BOND_YOY 永续债同比 (%)
    perpetual_bond_paybale_yoy = Field()  # PERPETUAL_BOND_PAYBALE_YOY 应付永续债同比 (%)
    predict_current_liab_yoy = Field()  # PREDICT_CURRENT_LIAB_YOY 预计流动负债同比 (%)
    predict_liab_yoy = Field()  # PREDICT_LIAB_YOY 预计负债同比 (%)
    preferred_shares_yoy = Field()  # PREFERRED_SHARES_YOY 优先股同比 (%)
    preferred_shares_paybale_yoy = Field()  # PREFERRED_SHARES_PAYBALE_YOY 应付优先股同比 (%)
    premium_rece_yoy = Field()  # PREMIUM_RECE_YOY 应收保费同比 (%)
    prepayment_yoy = Field()  # PREPAYMENT_YOY 预付款项同比 (%)
    productive_biology_asset_yoy = Field()  # PRODUCTIVE_BIOLOGY_ASSET_YOY 生产性生物资产同比 (%)
    project_material_yoy = Field()  # PROJECT_MATERIAL_YOY 工程物资同比 (%)
    rc_reserve_rece_yoy = Field()  # RC_RESERVE_RECE_YOY 应收再保险准备金同比 (%)
    reinsure_payable_yoy = Field()  # REINSURE_PAYABLE_YOY 应付再保险款同比 (%)
    reinsure_rece_yoy = Field()  # REINSURE_RECE_YOY 应收再保险款同比 (%)
    sell_repo_finasset_yoy = Field()  # SELL_REPO_FINASSET_YOY 卖出回购金融资产同比 (%)
    settle_excess_reserve_yoy = Field()  # SETTLE_EXCESS_RESERVE_YOY 结算备付金同比 (%)
    share_capital_yoy = Field()  # SHARE_CAPITAL_YOY 实收资本 (或股本)同比 (%)
    short_bond_payable_yoy = Field()  # SHORT_BOND_PAYABLE_YOY 短期应付债券同比 (%)
    short_fin_payable_yoy = Field()  # SHORT_FIN_PAYABLE_YOY 短期融资应付同比 (%)
    short_loan_yoy = Field()  # SHORT_LOAN_YOY 短期借款同比 (%)
    special_payable_yoy = Field()  # SPECIAL_PAYABLE_YOY 专项应付款同比 (%)
    special_reserve_yoy = Field()  # SPECIAL_RESERVE_YOY 专项储备同比 (%)
    staff_salary_payable_yoy = Field()  # STAFF_SALARY_PAYABLE_YOY 应付职工薪酬同比 (%)
    subsidy_rece_yoy = Field()  # SUBSIDY_RECE_YOY 应收补贴同比 (%)
    surplus_reserve_yoy = Field()  # SURPLUS_RESERVE_YOY 盈余公积同比 (%)
    tax_payable_yoy = Field()  # TAX_PAYABLE_YOY 应交税费同比 (%)
    total_assets_yoy = Field()  # TOTAL_ASSETS_YOY 资产总计同比 (%)
    total_current_assets_yoy = Field()  # TOTAL_CURRENT_ASSETS_YOY 流动资产合计同比 (%)
    total_current_liab_yoy = Field()  # TOTAL_CURRENT_LIAB_YOY 流动负债合计同比 (%)
    total_equity_yoy = Field()  # TOTAL_EQUITY_YOY 股东权益合计同比 (%)
    total_liab_equity_yoy = Field()  # TOTAL_LIAB_EQUITY_YOY 负债和股东权益总计同比 (%)
    total_liabilities_yoy = Field()  # TOTAL_LIABILITIES_YOY 负债合计同比 (%)
    total_noncurrent_assets_yoy = Field()  # TOTAL_NONCURRENT_ASSETS_YOY 非流动资产合计同比 (%)
    total_noncurrent_liab_yoy = Field()  # TOTAL_NONCURRENT_LIAB_YOY 非流动负债合计同比 (%)
    total_parent_equity_yoy = Field()  # TOTAL_PARENT_EQUITY_YOY 归属于母公司股东权益总计同比 (%)
    trade_finasset_yoy = Field()  # TRADE_FINASSET_YOY 交易性金融资产同比 (%)
    trade_finasset_notfvtpl_yoy = Field()  # TRADE_FINASSET_NOTFVTPL_YOY 非以公允价值计量且其变动计入当期损益的交易性金融资产同比 (%)
    trade_finliab_yoy = Field()  # TRADE_FINLIAB_YOY 交易性金融负债同比 (%)
    trade_finliab_notfvtpl_yoy = Field()  # TRADE_FINLIAB_NOTFVTPL_YOY 非以公允价值计量且其变动计入当期损益的交易性金融负债同比 (%)
    treasury_shares_yoy = Field()  # TREASURY_SHARES_YOY 减库存股同比 (%)
    unassign_rprofit_yoy = Field()  # UNASSIGN_RPOFIT_YOY 未分配利润同比 (%)
    unconfirm_invest_loss_yoy = Field()  # UNCONFIRM_INVEST_LOSS_YOY 未确认投资损失同比 (%)
    userright_asset_yoy = Field()  # USERIGHT_ASSET_YOY 使用权资产同比 (%)
    osopinion_type = Field()  # OSOPINION_TYPE 其他审计意见类型
    listing_state = Field()  # LISTING_STATE 上市状态


class IncomeStatementItem(Item):
    """
    利润表
    表明：listed_income_statement
    """
    pmid = Field()  # （secu_code + report_date）MD5 32位 业务主键
    stock_code = Field()  # SECUCODE 证券代码
    stock_name = Field()  # SECURITY_NAME_ABBR 股票简称
    security_code = Field()  # SECURITY_CODE 证券代码（不含交易所后缀）
    org_code = Field()  # ORG_CODE 组织代码
    org_type = Field()  # ORG_TYPE 组织类型
    report_date = Field()  # REPORT_DATE 报告日期
    report_type = Field()  # REPORT_TYPE 报告类型
    report_date_name = Field()  # REPORT_DATE_NAME 报告日期名称
    security_type_code = Field()  # SECURITY_TYPE_CODE 证券类型代码
    notice_date = Field()  # NOTICE_DATE 公告日期
    update_date = Field()  # UPDATE_DATE 更新日期
    currency = Field()  # CURRENCY 货币单位
    total_operate_income = Field()  # TOTAL_OPERATE_INCOME 营业总收入
    total_operate_income_yoy = Field()  # TOTAL_OPERATE_INCOME_YOY 营业总收入同比
    operate_income = Field()  # OPERATE_INCOME 营业收入
    operate_income_yoy = Field()  # OPERATE_INCOME_YOY 营业收入同比
    interest_income = Field()  # INTEREST_INCOME 利息收入
    interest_income_yoy = Field()  # INTEREST_INCOME_YOY 利息收入同比
    earned_premium = Field()  # EARNED_PREMIUM 已赚保费
    earned_premium_yoy = Field()  # EARNED_PREMIUM_YOY 已赚保费同比
    fee_commission_income = Field()  # FEE_COMMISSION_INCOME 手续费及佣金收入
    fee_commission_income_yoy = Field()  # FEE_COMMISSION_INCOME_YOY 手续费及佣金收入同比
    other_business_income = Field()  # OTHER_BUSINESS_INCOME 其他业务收入
    other_business_income_yoy = Field()  # OTHER_BUSINESS_INCOME_YOY 其他业务收入同比
    toi_other = Field()  # TOI_OTHER 营业总收入其他项
    toi_other_yoy = Field()  # TOI_OTHER_YOY 营业总收入其他项同比
    total_operate_cost = Field()  # TOTAL_OPERATE_COST 营业总成本
    total_operate_cost_yoy = Field()  # TOTAL_OPERATE_COST_YOY 营业总成本同比
    operate_cost = Field()  # OPERATE_COST 营业成本
    operate_cost_yoy = Field()  # OPERATE_COST_YOY 营业成本同比
    interest_expense = Field()  # INTEREST_EXPENSE 利息支出
    interest_expense_yoy = Field()  # INTEREST_EXPENSE_YOY 利息支出同比
    fee_commission_expense = Field()  # FEE_COMMISSION_EXPENSE 手续费及佣金支出
    fee_commission_expense_yoy = Field()  # FEE_COMMISSION_EXPENSE_YOY 手续费及佣金支出同比
    research_expense = Field()  # RESEARCH_EXPENSE 研发费用
    research_expense_yoy = Field()  # RESEARCH_EXPENSE_YOY 研发费用同比
    surrender_value = Field()  # SURRENDER_VALUE 退保金
    surrender_value_yoy = Field()  # SURRENDER_VALUE_YOY 退保金同比
    net_compensate_expense = Field()  # NET_COMPENSATE_EXPENSE 净赔付支出
    net_compensate_expense_yoy = Field()  # NET_COMPENSATE_EXPENSE_YOY 净赔付支出同比
    net_contract_reserve = Field()  # NET_CONTRACT_RESERVE 净合同准备金
    net_contract_reserve_yoy = Field()  # NET_CONTRACT_RESERVE_YOY 净合同准备金同比
    policy_bonus_expense = Field()  # POLICY_BONUS_EXPENSE 保单红利支出
    policy_bonus_expense_yoy = Field()  # POLICY_BONUS_EXPENSE_YOY 保单红利支出同比
    reinsure_expense = Field()  # REINSURE_EXPENSE 分保费用
    reinsure_expense_yoy = Field()  # REINSURE_EXPENSE_YOY 分保费用同比
    other_business_cost = Field()  # OTHER_BUSINESS_COST 其他业务成本
    other_business_cost_yoy = Field()  # OTHER_BUSINESS_COST_YOY 其他业务成本同比
    operate_tax_add = Field()  # OPERATE_TAX_ADD 营业税金及附加
    operate_tax_add_yoy = Field()  # OPERATE_TAX_ADD_YOY 营业税金及附加同比
    sale_expense = Field()  # SALE_EXPENSE 销售费用
    sale_expense_yoy = Field()  # SALE_EXPENSE_YOY 销售费用同比
    manage_expense = Field()  # MANAGE_EXPENSE 管理费用
    manage_expense_yoy = Field()  # MANAGE_EXPENSE_YOY 管理费用同比
    me_research_expense = Field()  # ME_RESEARCH_EXPENSE 管理费用中的研发费用
    me_research_expense_yoy = Field()  # ME_RESEARCH_EXPENSE_YOY 管理费用中的研发费用同比
    finance_expense = Field()  # FINANCE_EXPENSE 财务费用
    finance_expense_yoy = Field()  # FINANCE_EXPENSE_YOY 财务费用同比
    fe_interest_expense = Field()  # FE_INTEREST_EXPENSE 财务费用中的利息支出
    fe_interest_expense_yoy = Field()  # FE_INTEREST_EXPENSE_YOY 财务费用中的利息支出同比
    fe_interest_income = Field()  # FE_INTEREST_INCOME 财务费用中的利息收入
    fe_interest_income_yoy = Field()  # FE_INTEREST_INCOME_YOY 财务费用中的利息收入同比
    asset_impairment_loss = Field()  # ASSET_IMPAIRMENT_LOSS 资产减值损失
    asset_impairment_loss_yoy = Field()  # ASSET_IMPAIRMENT_LOSS_YOY 资产减值损失同比
    credit_impairment_loss = Field()  # CREDIT_IMPAIRMENT_LOSS 信用减值损失
    credit_impairment_loss_yoy = Field()  # CREDIT_IMPAIRMENT_LOSS_YOY 信用减值损失同比
    toc_other = Field()  # TOC_OTHER 营业总成本其他项
    toc_other_yoy = Field()  # TOC_OTHER_YOY 营业总成本其他项同比
    fairvalue_change_income = Field()  # FAIRVALUE_CHANGE_INCOME 公允价值变动收益
    fairvalue_change_income_yoy = Field()  # FAIRVALUE_CHANGE_INCOME_YOY 公允价值变动收益同比
    invest_income = Field()  # INVEST_INCOME 投资收益
    invest_income_yoy = Field()  # INVEST_INCOME_YOY 投资收益同比
    invest_joint_income = Field()  # INVEST_JOINT_INCOME 联营企业投资收益
    invest_joint_income_yoy = Field()  # INVEST_JOINT_INCOME_YOY 联营企业投资收益同比
    net_exposure_income = Field()  # NET_EXPOSURE_INCOME 净敞口收益
    net_exposure_income_yoy = Field()  # NET_EXPOSURE_INCOME_YOY 净敞口收益同比
    exchange_income = Field()  # EXCHANGE_INCOME 汇兑收益
    exchange_income_yoy = Field()  # EXCHANGE_INCOME_YOY 汇兑收益同比
    asset_disposal_income = Field()  # ASSET_DISPOSAL_INCOME 资产处置收益
    asset_disposal_income_yoy = Field()  # ASSET_DISPOSAL_INCOME_YOY 资产处置收益同比
    asset_impairment_income = Field()  # ASSET_IMPAIRMENT_INCOME 资产减值收益
    asset_impairment_income_yoy = Field()  # ASSET_IMPAIRMENT_INCOME_YOY 资产减值收益同比
    credit_impairment_income = Field()  # CREDIT_IMPAIRMENT_INCOME 信用减值收益
    credit_impairment_income_yoy = Field()  # CREDIT_IMPAIRMENT_INCOME_YOY 信用减值收益同比
    other_income = Field()  # OTHER_INCOME 其他收益
    other_income_yoy = Field()  # OTHER_INCOME_YOY 其他收益同比
    operate_profit_other = Field()  # OPERATE_PROFIT_OTHER 营业利润其他项
    operate_profit_other_yoy = Field()  # OPERATE_PROFIT_OTHER_YOY 营业利润其他项同比
    operate_profit_balance = Field()  # OPERATE_PROFIT_BALANCE 营业利润余额
    operate_profit_balance_yoy = Field()  # OPERATE_PROFIT_BALANCE_YOY 营业利润余额同比
    operate_profit = Field()  # OPERATE_PROFIT 营业利润
    operate_profit_yoy = Field()  # OPERATE_PROFIT_YOY 营业利润同比
    nonbusiness_income = Field()  # NONBUSINESS_INCOME 营业外收入
    nonbusiness_income_yoy = Field()  # NONBUSINESS_INCOME_YOY 营业外收入同比
    noncurrent_disposal_income = Field()  # NONCURRENT_DISPOSAL_INCOME 非流动资产处置收益
    noncurrent_disposal_income_yoy = Field()  # NONCURRENT_DISPOSAL_INCOME_YOY 非流动资产处置收益同比
    nonbusiness_expense = Field()  # NONBUSINESS_EXPENSE 营业外支出
    nonbusiness_expense_yoy = Field()  # NONBUSINESS_EXPENSE_YOY 营业外支出同比
    noncurrent_disposal_loss = Field()  # NONCURRENT_DISPOSAL_LOSS 非流动资产处置损失
    noncurrent_disposal_loss_yoy = Field()  # NONCURRENT_DISPOSAL_LOSS_YOY 非流动资产处置损失同比
    effect_tp_other = Field()  # EFFECT_TP_OTHER 其他影响利润总额项
    effect_tp_other_yoy = Field()  # EFFECT_TP_OTHER_YOY 其他影响利润总额项同比
    total_profit_balance = Field()  # TOTAL_PROFIT_BALANCE 利润总额余额
    total_profit_balance_yoy = Field()  # TOTAL_PROFIT_BALANCE_YOY 利润总额余额同比
    total_profit = Field()  # TOTAL_PROFIT 利润总额
    total_profit_yoy = Field()  # TOTAL_PROFIT_YOY 利润总额同比
    income_tax = Field()  # INCOME_TAX 所得税费用
    income_tax_yoy = Field()  # INCOME_TAX_YOY 所得税费用同比
    effect_netprofit_other = Field()  # EFFECT_NETPROFIT_OTHER 其他影响净利润项
    effect_netprofit_other_yoy = Field()  # EFFECT_NETPROFIT_OTHER_YOY 其他影响净利润项同比
    effect_netprofit_balance = Field()  # EFFECT_NETPROFIT_BALANCE 净利润影响余额
    effect_netprofit_balance_yoy = Field()  # EFFECT_NETPROFIT_BALANCE_YOY 净利润影响余额同比
    unconfirm_invest_loss = Field()  # UNCONFIRM_INVEST_LOSS 未确认投资损失
    unconfirm_invest_loss_yoy = Field()  # UNCONFIRM_INVEST_LOSS_YOY 未确认投资损失同比
    netprofit = Field()  # NETPROFIT 净利润
    netprofit_yoy = Field()  # NETPROFIT_YOY 净利润同比
    precombine_profit = Field()  # PRECOMBINE_PROFIT 合并前利润
    precombine_profit_yoy = Field()  # PRECOMBINE_PROFIT_YOY 合并前利润同比
    continued_netprofit = Field()  # CONTINUED_NETPROFIT 持续经营净利润
    continued_netprofit_yoy = Field()  # CONTINUED_NETPROFIT_YOY 持续经营净利润同比
    discontinued_netprofit = Field()  # DISCONTINUED_NETPROFIT 终止经营净利润
    discontinued_netprofit_yoy = Field()  # DISCONTINUED_NETPROFIT_YOY 终止经营净利润同比
    parent_netprofit = Field()  # PARENT_NETPROFIT 归母净利润
    parent_netprofit_yoy = Field()  # PARENT_NETPROFIT_YOY 归母净利润同比
    minority_interest = Field()  # MINORITY_INTEREST 少数股东损益
    minority_interest_yoy = Field()  # MINORITY_INTEREST_YOY 少数股东损益同比
    deduct_parent_netprofit = Field()  # DEDUCT_PARENT_NETPROFIT 扣非归母净利润
    deduct_parent_netprofit_yoy = Field()  # DEDUCT_PARENT_NETPROFIT_YOY 扣非归母净利润同比
    netprofit_other = Field()  # NETPROFIT_OTHER 净利润其他项
    netprofit_other_yoy = Field()  # NETPROFIT_OTHER_YOY 净利润其他项同比
    netprofit_balance = Field()  # NETPROFIT_BALANCE 净利润余额
    netprofit_balance_yoy = Field()  # NETPROFIT_BALANCE_YOY 净利润余额同比
    basic_eps = Field()  # BASIC_EPS 基本每股收益
    basic_eps_yoy = Field()  # BASIC_EPS_YOY 基本每股收益同比
    diluted_eps = Field()  # DILUTED_EPS 稀释每股收益
    diluted_eps_yoy = Field()  # DILUTED_EPS_YOY 稀释每股收益同比
    other_compre_income = Field()  # OTHER_COMPRE_INCOME 其他综合收益
    other_compre_income_yoy = Field()  # OTHER_COMPRE_INCOME_YOY 其他综合收益同比
    parent_oci = Field()  # PARENT_OCI 归母其他综合收益
    parent_oci_yoy = Field()  # PARENT_OCI_YOY 归母其他综合收益同比
    minority_oci = Field()  # MINORITY_OCI 少数股东其他综合收益
    minority_oci_yoy = Field()  # MINORITY_OCI_YOY 少数股东其他综合收益同比
    parent_oci_other = Field()  # PARENT_OCI_OTHER 归母其他综合收益其他项
    parent_oci_other_yoy = Field()  # PARENT_OCI_OTHER_YOY 归母其他综合收益其他项同比
    parent_oci_balance = Field()  # PARENT_OCI_BALANCE 归母其他综合收益余额
    parent_oci_balance_yoy = Field()  # PARENT_OCI_BALANCE_YOY 归母其他综合收益余额同比
    unable_oci = Field()  # UNABLE_OCI 不可重分类其他综合收益
    unable_oci_yoy = Field()  # UNABLE_OCI_YOY 不可重分类其他综合收益同比
    creditrisk_fairvalue_change = Field()  # CREDITRISK_FAIRVALUE_CHANGE 信用风险公允价值变动
    creditrisk_fairvalue_change_yoy = Field()  # CREDITRISK_FAIRVALUE_CHANGE_YOY 信用风险公允价值变动同比
    otherright_fairvalue_change = Field()  # OTHERRIGHT_FAIRVALUE_CHANGE 其他权益工具公允价值变动
    otherright_fairvalue_change_yoy = Field()  # OTHERRIGHT_FAIRVALUE_CHANGE_YOY 其他权益工具公允价值变动同比
    setup_profit_change = Field()  # SETUP_PROFIT_CHANGE 设立利润变动
    setup_profit_change_yoy = Field()  # SETUP_PROFIT_CHANGE_YOY 设立利润变动同比
    rightlaw_unable_oci = Field()  # RIGHTLAW_UNABLE_OCI 权益法下不可重分类其他综合收益
    rightlaw_unable_oci_yoy = Field()  # RIGHTLAW_UNABLE_OCI_YOY 权益法下不可重分类其他综合收益同比
    unable_oci_other = Field()  # UNABLE_OCI_OTHER 不可重分类其他综合收益其他项
    unable_oci_other_yoy = Field()  # UNABLE_OCI_OTHER_YOY 不可重分类其他综合收益其他项同比
    unable_oci_balance = Field()  # UNABLE_OCI_BALANCE 不可重分类其他综合收益余额
    unable_oci_balance_yoy = Field()  # UNABLE_OCI_BALANCE_YOY 不可重分类其他综合收益余额同比
    able_oci = Field()  # ABLE_OCI 可重分类其他综合收益
    able_oci_yoy = Field()  # ABLE_OCI_YOY 可重分类其他综合收益同比
    rightlaw_able_oci = Field()  # RIGHTLAW_ABLE_OCI 权益法下可重分类其他综合收益
    rightlaw_able_oci_yoy = Field()  # RIGHTLAW_ABLE_OCI_YOY 权益法下可重分类其他综合收益同比
    afa_fairvalue_change = Field()  # AFA_FAIRVALUE_CHANGE 可供出售金融资产公允价值变动
    afa_fairvalue_change_yoy = Field()  # AFA_FAIRVALUE_CHANGE_YOY 可供出售金融资产公允价值变动同比
    hmi_afa = Field()  # HMI_AFA 持有至到期投资
    hmi_afa_yoy = Field()  # HMI_AFA_YOY 持有至到期投资同比
    cashflow_hedge_valid = Field()  # CASHFLOW_HEDGE_VALID 现金流套期保值有效部分
    cashflow_hedge_valid_yoy = Field()  # CASHFLOW_HEDGE_VALID_YOY 现金流套期保值有效部分同比
    creditor_fairvalue_change = Field()  # CREDITOR_FAIRVALUE_CHANGE 债权公允价值变动
    creditor_fairvalue_change_yoy = Field()  # CREDITOR_FAIRVALUE_CHANGE_YOY 债权公允价值变动同比
    creditor_impairment_reserve = Field()  # CREDITOR_IMPAIRMENT_RESERVE 债权减值准备
    creditor_impairment_reserve_yoy = Field()  # CREDITOR_IMPAIRMENT_RESERVE_YOY 债权减值准备同比
    finance_oci_amt = Field()  # FINANCE_OCI_AMT 财务其他综合收益金额
    finance_oci_amt_yoy = Field()  # FINANCE_OCI_AMT_YOY 财务其他综合收益金额同比
    convert_diff = Field()  # CONVERT_DIFF 折算差额
    convert_diff_yoy = Field()  # CONVERT_DIFF_YOY 折算差额同比
    able_oci_other = Field()  # ABLE_OCI_OTHER 可重分类其他综合收益其他项
    able_oci_other_yoy = Field()  # ABLE_OCI_OTHER_YOY 可重分类其他综合收益其他项同比
    able_oci_balance = Field()  # ABLE_OCI_BALANCE 可重分类其他综合收益余额
    able_oci_balance_yoy = Field()  # ABLE_OCI_BALANCE_YOY 可重分类其他综合收益余额同比
    oci_other = Field()  # OCI_OTHER 其他综合收益其他项
    oci_other_yoy = Field()  # OCI_OTHER_YOY 其他综合收益其他项同比
    oci_balance = Field()  # OCI_BALANCE 其他综合收益余额
    oci_balance_yoy = Field()  # OCI_BALANCE_YOY 其他综合收益余额同比
    total_compre_income = Field()  # TOTAL_COMPRE_INCOME 综合收益总额
    total_compre_income_yoy = Field()  # TOTAL_COMPRE_INCOME_YOY 综合收益总额同比
    parent_tci = Field()  # PARENT_TCI 归母综合收益
    parent_tci_yoy = Field()  # PARENT_TCI_YOY 归母综合收益同比
    minority_tci = Field()  # MINORITY_TCI 少数股东综合收益
    minority_tci_yoy = Field()  # MINORITY_TCI_YOY 少数股东综合收益同比
    precombine_tci = Field()  # PRECOMBINE_TCI 合并前综合收益
    precombine_tci_yoy = Field()  # PRECOMBINE_TCI_YOY 合并前综合收益同比
    effect_tci_balance = Field()  # EFFECT_TCI_BALANCE 综合收益影响余额
    effect_tci_balance_yoy = Field()  # EFFECT_TCI_BALANCE_YOY 综合收益影响余额同比
    tci_other = Field()  # TCI_OTHER 综合收益其他项
    tci_other_yoy = Field()  # TCI_OTHER_YOY 综合收益其他项同比
    tci_balance = Field()  # TCI_BALANCE 综合收益余额
    tci_balance_yoy = Field()  # TCI_BALANCE_YOY 综合收益余额同比
    acf_end_income = Field()  # ACF_END_INCOME 会计期间末收入
    acf_end_income_yoy = Field()  # ACF_END_INCOME_YOY 会计期间末收入同比
    opinion_type = Field()  # OPINION_TYPE 审计意见类型


class CashflowStatementItem(Item):
    """
    现金流量表
    表明：listed_statement_of_cash_flows
    """
    pmid = Field()  # （secu_code + report_date）MD5 32位 业务主键
    stock_code = Field()  # SECUCODE 证券代码
    stock_name = Field()  # SECURITY_NAME_ABBR 股票简称
    security_code = Field()  # SECURITY_CODE 证券代码（不含交易所后缀）
    org_code = Field()  # ORG_CODE 组织代码
    org_type = Field()  # ORG_TYPE 组织类型
    report_date = Field()  # REPORT_DATE 报告日期
    report_type = Field()  # REPORT_TYPE 报告类型
    report_date_name = Field()  # REPORT_DATE_NAME 报告日期名称
    security_type_code = Field()  # SECURITY_TYPE_CODE 证券类型代码
    notice_date = Field()  # NOTICE_DATE 公告日期
    update_date = Field()  # UPDATE_DATE 更新日期
    currency = Field()  # CURRENCY 货币单位
    sales_services = Field()  # SALES_SERVICES 销售商品、提供劳务收到的现金
    deposit_interbank_add = Field()  # DEPOSIT_INTERBANK_ADD 吸收存款及同业存放款项增加额
    loan_pbc_add = Field()  # LOAN_PBC_ADD 向中央银行借款增加额
    ofi_bf_add = Field()  # OFI_BF_ADD 向其他金融机构拆入资金增加额
    receive_origic_premium = Field()  # RECEIVE_ORIGIC_PREMIUM 收到原保险保费的现金
    receive_reinsure_net = Field()  # RECEIVE_REINSURE_NET 收到再保险业务净现金
    insured_invest_add = Field()  # INSURED_INVEST_ADD 保户投资款增加额
    disposal_tfa_add = Field()  # DISPOSAL_TFA_ADD 处置交易性金融资产增加额
    receive_interest_commission = Field()  # RECEIVE_INTEREST_COMMISSION 收到利息及手续费的现金
    borrow_fund_add = Field()  # BORROW_FUND_ADD 借入资金增加额
    loan_advance_reduce = Field()  # LOAN_ADVANCE_REDUCE 贷款及垫款减少额
    repo_business_add = Field()  # REPO_BUSINESS_ADD 回购业务增加额
    receive_tax_refund = Field()  # RECEIVE_TAX_REFUND 收到的税收返还
    receive_other_operate = Field()  # RECEIVE_OTHER_OPERATE 收到其他与经营活动有关的现金
    operate_inflow_other = Field()  # OPERATE_INFLOW_OTHER 经营活动现金流入其他项
    operate_inflow_balance = Field()  # OPERATE_INFLOW_BALANCE 经营活动现金流入余额
    total_operate_inflow = Field()  # TOTAL_OPERATE_INFLOW 经营活动现金流入总额
    buy_services = Field()  # BUY_SERVICES 购买商品、接受劳务支付的现金/经营活动现金流入小计
    loan_advance_add = Field()  # LOAN_ADVANCE_ADD 贷款及垫款增加额
    pbc_interbank_add = Field()  # PBC_INTERBANK_ADD 存放中央银行及同业款项增加额
    pay_origic_compensate = Field()  # PAY_ORIGIC_COMPENSATE 支付原保险赔付的现金
    pay_interest_commission = Field()  # PAY_INTEREST_COMMISSION 支付利息及手续费的现金
    pay_policy_bonus = Field()  # PAY_POLICY_BONUS 支付保单红利的现金
    pay_staff_cash = Field()  # PAY_STAFF_CASH 支付给职工以及为职工支付的现金
    pay_all_tax = Field()  # PAY_ALL_TAX 支付的各项税费
    pay_other_operate = Field()  # PAY_OTHER_OPERATE 支付其他与经营活动有关的现金
    operate_outflow_other = Field()  # OPERATE_OUTFLOW_OTHER 经营活动现金流出其他项
    operate_outflow_balance = Field()  # OPERATE_OUTFLOW_BALANCE 经营活动现金流出余额
    total_operate_outflow = Field()  # TOTAL_OPERATE_OUTFLOW 经营活动现金流出总额
    operate_netcash_other = Field()  # OPERATE_NETCASH_OTHER 经营活动净现金流其他项
    operate_netcash_balance = Field()  # OPERATE_NETCASH_BALANCE 经营活动净现金流余额
    netcash_operate = Field()  # NETCASH_OPERATE 经营活动产生的现金流量净额
    withdraw_invest = Field()  # WITHDRAW_INVEST 收回投资收到的现金
    receive_invest_income = Field()  # RECEIVE_INVEST_INCOME 取得投资收益收到的现金
    disposal_long_asset = Field()  # DISPOSAL_LONG_ASSET 处置固定资产、无形资产等长期资产收到的现金/处置固定资产、无形资产和其他长期资产收回的现金净额
    disposal_subsidiary_other = Field()  # DISPOSAL_SUBSIDIARY_OTHER 处置子公司及其他营业单位收到的现金
    reduce_pledge_timedeposits = Field()  # REDUCE_PLEDGE_TIMEDEPOSITS 减少质押及定期存款收到的现金
    receive_other_invest = Field()  # RECEIVE_OTHER_INVEST 收到其他与投资活动有关的现金
    invest_inflow_other = Field()  # INVEST_INFLOW_OTHER 投资活动现金流入其他项
    invest_inflow_balance = Field()  # INVEST_INFLOW_BALANCE 投资活动现金流入余额
    total_invest_inflow = Field()  # TOTAL_INVEST_INFLOW 投资活动现金流入总额/投资活动现金流入小计
    construct_long_asset = Field()  # CONSTRUCT_LONG_ASSET 购建固定资产、无形资产等长期资产支付的现金/购建固定资产、无形资产和其他长期资产支付的现金
    invest_pay_cash = Field()  # INVEST_PAY_CASH 投资支付的现金
    pledge_loan_add = Field()  # PLEDGE_LOAN_ADD 质押贷款增加额
    obtain_subsidiary_other = Field()  # OBTAIN_SUBSIDIARY_OTHER 取得子公司及其他营业单位支付的现金/取得子公司及其他营业单位支付的现金净额
    add_pledge_timedeposits = Field()  # ADD_PLEDGE_TIMEDEPOSITS 增加质押及定期存款支付的现金
    pay_other_invest = Field()  # PAY_OTHER_INVEST 支付其他与投资活动有关的现金
    invest_outflow_other = Field()  # INVEST_OUTFLOW_OTHER 投资活动现金流出其他项
    invest_outflow_balance = Field()  # INVEST_OUTFLOW_BALANCE 投资活动现金流出余额
    total_invest_outflow = Field()  # TOTAL_INVEST_OUTFLOW 投资活动现金流出总额
    invest_netcash_other = Field()  # INVEST_NETCASH_OTHER 投资活动净现金流其他项
    invest_netcash_balance = Field()  # INVEST_NETCASH_BALANCE 投资活动净现金流余额
    netcash_invest = Field()  # NETCASH_INVEST 投资活动产生的现金流量净额
    accept_invest_cash = Field()  # ACCEPT_INVEST_CASH 吸收投资收到的现金
    subsidiary_accept_invest = Field()  # SUBSIDIARY_ACCEPT_INVEST 子公司吸收投资收到的现金
    receive_loan_cash = Field()  # RECEIVE_LOAN_CASH 取得借款收到的现金
    issue_bond = Field()  # ISSUE_BOND 发行债券收到的现金
    receive_other_finance = Field()  # RECEIVE_OTHER_FINANCE 收到其他与筹资活动有关的现金
    finance_inflow_other = Field()  # FINANCE_INFLOW_OTHER 筹资活动现金流入其他项
    finance_inflow_balance = Field()  # FINANCE_INFLOW_BALANCE 筹资活动现金流入余额
    total_finance_inflow = Field()  # TOTAL_FINANCE_INFLOW 筹资活动现金流入总额
    pay_debt_cash = Field()  # PAY_DEBT_CASH 偿还债务支付的现金
    assign_dividend_porfit = Field()  # ASSIGN_DIVIDEND_PORFIT 分配股利、利润或偿付利息支付的现金
    subsidiary_pay_dividend = Field()  # SUBSIDIARY_PAY_DIVIDEND 子公司支付股利或利润的现金
    buy_subsidiary_equity = Field()  # BUY_SUBSIDIARY_EQUITY 购买子公司股权支付的现金
    pay_other_finance = Field()  # PAY_OTHER_FINANCE 支付其他与筹资活动有关的现金
    subsidiary_reduce_cash = Field()  # SUBSIDIARY_REDUCE_CASH 子公司减少注册资本支付的现金
    finance_outflow_other = Field()  # FINANCE_OUTFLOW_OTHER 筹资活动现金流出其他项
    finance_outflow_balance = Field()  # FINANCE_OUTFLOW_BALANCE 筹资活动现金流出余额
    total_finance_outflow = Field()  # TOTAL_FINANCE_OUTFLOW 筹资活动现金流出总额
    finance_netcash_other = Field()  # FINANCE_NETCASH_OTHER 筹资活动净现金流其他项
    finance_netcash_balance = Field()  # FINANCE_NETCASH_BALANCE 筹资活动净现金流余额
    netcash_finance = Field()  # NETCASH_FINANCE 筹资活动产生的现金流量净额
    rate_change_effect = Field()  # RATE_CHANGE_EFFECT 汇率变动对现金及现金等价物的影响
    cce_add_other = Field()  # CCE_ADD_OTHER 现金及现金等价物增加额其他项
    cce_add_balance = Field()  # CCE_ADD_BALANCE 现金及现金等价物增加额余额
    cce_add = Field()  # CCE_ADD 现金及现金等价物净增加额
    begin_cce = Field()  # BEGIN_CCE 期初现金及现金等价物余额
    end_cce_other = Field()  # END_CCE_OTHER 期末现金及现金等价物其他项
    end_cce_balance = Field()  # END_CCE_BALANCE 期末现金及现金等价物余额
    end_cce = Field()  # END_CCE 期末现金及现金等价物总额
    netprofit = Field()  # NETPROFIT 净利润
    asset_impairment = Field()  # ASSET_IMPAIRMENT 资产减值准备
    fa_ir_depr = Field()  # FA_IR_DEPR 固定资产及投资性房地产折旧
    oilgas_biology_depr = Field()  # OILGAS_BIOLOGY_DEPR 油气资产及生物资产折旧
    ir_depr = Field()  # IR_DEPR 投资性房地产折旧
    ia_amortize = Field()  # IA_AMORTIZE 无形资产摊销
    lpe_amortize = Field()  # LPE_AMORTIZE 长期待摊费用摊销
    defer_income_amortize = Field()  # DEFER_INCOME_AMORTIZE 递延收益摊销
    prepaid_expense_reduce = Field()  # PREPAID_EXPENSE_REDUCE 预付费用减少额
    accrued_expense_add = Field()  # ACCRUED_EXPENSE_ADD 应计费用增加额
    disposal_longasset_loss = Field()  # DISPOSAL_LONGASSET_LOSS 处置长期资产损失
    fa_scrap_loss = Field()  # FA_SCRAP_LOSS 固定资产报废损失
    fairvalue_change_loss = Field()  # FAIRVALUE_CHANGE_LOSS 公允价值变动损失
    finance_expense = Field()  # FINANCE_EXPENSE 财务费用
    invest_loss = Field()  # INVEST_LOSS 投资损失
    defer_tax = Field()  # DEFER_TAX 递延所得税
    dt_asset_reduce = Field()  # DT_ASSET_REDUCE 递延所得税资产减少额
    dt_liab_add = Field()  # DT_LIAB_ADD 递延所得税负债增加额
    predict_liab_add = Field()  # PREDICT_LIAB_ADD 预计负债增加额
    inventory_reduce = Field()  # INVENTORY_REDUCE 存货减少额
    operate_rece_reduce = Field()  # OPERATE_RECE_REDUCE 经营性应收项目减少额
    operate_payable_add = Field()  # OPERATE_PAYABLE_ADD 经营性应付项目增加额
    other = Field()  # OTHER 其他调整项
    operate_netcash_othernote = Field()  # OPERATE_NETCASH_OTHERNOTE 经营活动净现金流其他调整项/经营活动产生的现金流量净额其他项目
    operate_netcash_balancenote = Field()  # OPERATE_NETCASH_BALANCENOTE 经营活动净现金流余额调整项/ 经营活动产生的现金流量净额平衡项目
    netcash_operatenote = Field()  # NETCASH_OPERATENOTE 经营活动净现金流调整总额
    debt_transfer_capital = Field()  # DEBT_TRANSFER_CAPITAL 债务转为资本的现金
    convert_bond_1year = Field()  # CONVERT_BOND_1YEAR 一年内到期的可转换公司债券
    finlease_obtain_fa = Field()  # FINLEASE_OBTAIN_FA 融资租赁取得的固定资产
    uninvolve_investfin_other = Field()  # UNINVOLVE_INVESTFIN_OTHER 不涉及投资和筹资的现金其他项
    end_cash = Field()  # END_CASH 期末现金余额
    begin_cash = Field()  # BEGIN_CASH 期初现金余额
    end_cash_equivalents = Field()  # END_CASH_EQUIVALENTS 期末现金等价物余额
    begin_cash_equivalents = Field()  # BEGIN_CASH_EQUIVALENTS 期初现金等价物余额
    cce_add_othernote = Field()  # CCE_ADD_OTHERNOTE 现金及现金等价物增加额其他调整项
    cce_add_balancenote = Field()  # CCE_ADD_BALANCENOTE 现金及现金等价物增加额余额调整项
    cce_addnote = Field()  # CCE_ADDNOTE 现金及现金等价物增加额调整总额
    sales_services_yoy = Field()  # SALES_SERVICES_YOY 销售商品、提供劳务收到的现金同比
    deposit_interbank_add_yoy = Field()  # DEPOSIT_INTERBANK_ADD_YOY 吸收存款及同业存放款项增加额同比
    loan_pbc_add_yoy = Field()  # LOAN_PBC_ADD_YOY 向中央银行借款增加额同比
    ofi_bf_add_yoy = Field()  # OFI_BF_ADD_YOY 向其他金融机构拆入资金增加额同比
    receive_origic_premium_yoy = Field()  # RECEIVE_ORIGIC_PREMIUM_YOY 收到原保险保费的现金同比
    receive_reinsure_net_yoy = Field()  # RECEIVE_REINSURE_NET_YOY 收到再保险业务净现金同比
    insured_invest_add_yoy = Field()  # INSURED_INVEST_ADD_YOY 保户投资款增加额同比
    disposal_tfa_add_yoy = Field()  # DISPOSAL_TFA_ADD_YOY 处置交易性金融资产增加额同比
    receive_interest_commission_yoy = Field()  # RECEIVE_INTEREST_COMMISSION_YOY 收到利息及手续费的现金同比
    borrow_fund_add_yoy = Field()  # BORROW_FUND_ADD_YOY 借入资金增加额同比
    loan_advance_reduce_yoy = Field()  # LOAN_ADVANCE_REDUCE_YOY 贷款及垫款减少额同比
    repo_business_add_yoy = Field()  # REPO_BUSINESS_ADD_YOY 回购业务增加额同比
    receive_tax_refund_yoy = Field()  # RECEIVE_TAX_REFUND_YOY 收到税费返还的现金同比
    receive_other_operate_yoy = Field()  # RECEIVE_OTHER_OPERATE_YOY 收到其他与经营活动有关的现金同比
    operate_inflow_other_yoy = Field()  # OPERATE_INFLOW_OTHER_YOY 经营活动现金流入其他项同比
    operate_inflow_balance_yoy = Field()  # OPERATE_INFLOW_BALANCE_YOY 经营活动现金流入余额同比
    total_operate_inflow_yoy = Field()  # TOTAL_OPERATE_INFLOW_YOY 经营活动现金流入总额同比
    buy_services_yoy = Field()  # BUY_SERVICES_YOY 购买商品、接受劳务支付的现金同比
    loan_advance_add_yoy = Field()  # LOAN_ADVANCE_ADD_YOY 贷款及垫款增加额同比
    pbc_interbank_add_yoy = Field()  # PBC_INTERBANK_ADD_YOY 存放中央银行及同业款项增加额同比
    pay_origic_compensate_yoy = Field()  # PAY_ORIGIC_COMPENSATE_YOY 支付原保险赔付的现金同比
    pay_interest_commission_yoy = Field()  # PAY_INTEREST_COMMISSION_YOY 支付利息及手续费的现金同比
    pay_policy_bonus_yoy = Field()  # PAY_POLICY_BONUS_YOY 支付保单红利的现金同比
    pay_staff_cash_yoy = Field()  # PAY_STAFF_CASH_YOY 支付给职工以及为职工支付的现金同比
    pay_all_tax_yoy = Field()  # PAY_ALL_TAX_YOY 支付的各项税费同比
    pay_other_operate_yoy = Field()  # PAY_OTHER_OPERATE_YOY 支付其他与经营活动有关的现金同比
    operate_outflow_other_yoy = Field()  # OPERATE_OUTFLOW_OTHER_YOY 经营活动现金流出其他项同比
    operate_outflow_balance_yoy = Field()  # OPERATE_OUTFLOW_BALANCE_YOY 经营活动现金流出余额同比
    total_operate_outflow_yoy = Field()  # TOTAL_OPERATE_OUTFLOW_YOY 经营活动现金流出总额同比
    operate_netcash_other_yoy = Field()  # OPERATE_NETCASH_OTHER_YOY 经营活动净现金流其他项同比
    operate_netcash_balance_yoy = Field()  # OPERATE_NETCASH_BALANCE_YOY 经营活动净现金流余额同比
    netcash_operate_yoy = Field()  # NETCASH_OPERATE_YOY 经营活动产生的现金流量净额同比
    withdraw_invest_yoy = Field()  # WITHDRAW_INVEST_YOY 收回投资收到的现金同比
    receive_invest_income_yoy = Field()  # RECEIVE_INVEST_INCOME_YOY 取得投资收益收到的现金同比
    disposal_long_asset_yoy = Field()  # DISPOSAL_LONG_ASSET_YOY 处置固定资产、无形资产等长期资产收到的现金同比
    disposal_subsidiary_other_yoy = Field()  # DISPOSAL_SUBSIDIARY_OTHER_YOY 处置子公司及其他营业单位收到的现金同比
    reduce_pledge_timedeposits_yoy = Field()  # REDUCE_PLEDGE_TIMEDEPOSITS_YOY 减少质押及定期存款收到的现金同比
    receive_other_invest_yoy = Field()  # RECEIVE_OTHER_INVEST_YOY 收到其他与投资活动有关的现金同比
    invest_inflow_other_yoy = Field()  # INVEST_INFLOW_OTHER_YOY 投资活动现金流入其他项同比
    invest_inflow_balance_yoy = Field()  # INVEST_INFLOW_BALANCE_YOY 投资活动现金流入余额同比
    total_invest_inflow_yoy = Field()  # TOTAL_INVEST_INFLOW_YOY 投资活动现金流入总额同比
    construct_long_asset_yoy = Field()  # CONSTRUCT_LONG_ASSET_YOY 购建固定资产、无形资产等长期资产支付的现金同比
    invest_pay_cash_yoy = Field()  # INVEST_PAY_CASH_YOY 投资支付的现金同比
    pledge_loan_add_yoy = Field()  # PLEDGE_LOAN_ADD_YOY 质押贷款增加额同比
    obtain_subsidiary_other_yoy = Field()  # OBTAIN_SUBSIDIARY_OTHER_YOY 取得子公司及其他营业单位支付的现金同比
    add_pledge_timedeposits_yoy = Field()  # ADD_PLEDGE_TIMEDEPOSITS_YOY 增加质押及定期存款支付的现金同比
    pay_other_invest_yoy = Field()  # PAY_OTHER_INVEST_YOY 支付其他与投资活动有关的现金同比
    invest_outflow_other_yoy = Field()  # INVEST_OUTFLOW_OTHER_YOY 投资活动现金流出其他项同比
    invest_outflow_balance_yoy = Field()  # INVEST_OUTFLOW_BALANCE_YOY 投资活动现金流出余额同比
    total_invest_outflow_yoy = Field()  # TOTAL_INVEST_OUTFLOW_YOY 投资活动现金流出总额同比
    invest_netcash_other_yoy = Field()  # INVEST_NETCASH_OTHER_YOY 投资活动净现金流其他项同比
    invest_netcash_balance_yoy = Field()  # INVEST_NETCASH_BALANCE_YOY 投资活动净现金流余额同比
    netcash_invest_yoy = Field()  # NETCASH_INVEST_YOY 投资活动产生的现金流量净额同比
    accept_invest_cash_yoy = Field()  # ACCEPT_INVEST_CASH_YOY 吸收投资收到的现金同比
    subsidiary_accept_invest_yoy = Field()  # SUBSIDIARY_ACCEPT_INVEST_YOY 子公司吸收投资收到的现金同比
    receive_loan_cash_yoy = Field()  # RECEIVE_LOAN_CASH_YOY 取得借款收到的现金同比
    issue_bond_yoy = Field()  # ISSUE_BOND_YOY 发行债券收到的现金同比
    receive_other_finance_yoy = Field()  # RECEIVE_OTHER_FINANCE_YOY 收到其他与筹资活动有关的现金同比
    finance_inflow_other_yoy = Field()  # FINANCE_INFLOW_OTHER_YOY 筹资活动现金流入其他项同比
    finance_inflow_balance_yoy = Field()  # FINANCE_INFLOW_BALANCE_YOY 筹资活动现金流入余额同比
    total_finance_inflow_yoy = Field()  # TOTAL_FINANCE_INFLOW_YOY 筹资活动现金流入总额同比
    pay_debt_cash_yoy = Field()  # PAY_DEBT_CASH_YOY 偿还债务支付的现金同比
    assign_dividend_porfit_yoy = Field()  # ASSIGN_DIVIDEND_PORFIT_YOY 分配股利、利润或偿付利息支付的现金同比
    subsidiary_pay_dividend_yoy = Field()  # SUBSIDIARY_PAY_DIVIDEND_YOY 子公司支付股利或利润的现金同比
    buy_subsidiary_equity_yoy = Field()  # BUY_SUBSIDIARY_EQUITY_YOY 购买子公司股权支付的现金同比
    pay_other_finance_yoy = Field()  # PAY_OTHER_FINANCE_YOY 支付其他与筹资活动有关的现金同比
    subsidiary_reduce_cash_yoy = Field()  # SUBSIDIARY_REDUCE_CASH_YOY 子公司减少注册资本支付的现金同比
    finance_outflow_other_yoy = Field()  # FINANCE_OUTFLOW_OTHER_YOY 筹资活动现金流出其他项同比
    finance_outflow_balance_yoy = Field()  # FINANCE_OUTFLOW_BALANCE_YOY 筹资活动现金流出余额同比
    total_finance_outflow_yoy = Field()  # TOTAL_FINANCE_OUTFLOW_YOY 筹资活动现金流出总额同比
    finance_netcash_other_yoy = Field()  # FINANCE_NETCASH_OTHER_YOY 筹资活动净现金流其他项同比
    finance_netcash_balance_yoy = Field()  # FINANCE_NETCASH_BALANCE_YOY 筹资活动净现金流余额同比
    netcash_finance_yoy = Field()  # NETCASH_FINANCE_YOY 筹资活动产生的现金流量净额同比
    rate_change_effect_yoy = Field()  # RATE_CHANGE_EFFECT_YOY 汇率变动对现金及现金等价物的影响同比
    cce_add_other_yoy = Field()  # CCE_ADD_OTHER_YOY 现金及现金等价物增加额其他项同比
    cce_add_balance_yoy = Field()  # CCE_ADD_BALANCE_YOY 现金及现金等价物增加额余额同比
    cce_add_yoy = Field()  # CCE_ADD_YOY 现金及现金等价物净增加额同比
    begin_cce_yoy = Field()  # BEGIN_CCE_YOY 期初现金及现金等价物余额同比
    end_cce_other_yoy = Field()  # END_CCE_OTHER_YOY 期末现金及现金等价物其他项同比
    end_cce_balance_yoy = Field()  # END_CCE_BALANCE_YOY 期末现金及现金等价物余额同比
    end_cce_yoy = Field()  # END_CCE_YOY 期末现金及现金等价物总额同比
    netprofit_yoy = Field()  # NETPROFIT_YOY 净利润同比
    asset_impairment_yoy = Field()  # ASSET_IMPAIRMENT_YOY 资产减值准备同比
    fa_ir_depr_yoy = Field()  # FA_IR_DEPR_YOY 固定资产及投资性房地产折旧同比
    oilgas_biology_depr_yoy = Field()  # OILGAS_BIOLOGY_DEPR_YOY 油气资产及生物资产折旧同比
    ir_depr_yoy = Field()  # IR_DEPR_YOY 投资性房地产折旧同比
    ia_amortize_yoy = Field()  # IA_AMORTIZE_YOY 无形资产摊销同比
    lpe_amortize_yoy = Field()  # LPE_AMORTIZE_YOY 长期待摊费用摊销同比
    defer_income_amortize_yoy = Field()  # DEFER_INCOME_AMORTIZE_YOY 递延收益摊销同比
    prepaid_expense_reduce_yoy = Field()  # PREPAID_EXPENSE_REDUCE_YOY 预付费用减少额同比
    accrued_expense_add_yoy = Field()  # ACCRUED_EXPENSE_ADD_YOY 应计费用增加额同比
    disposal_longasset_loss_yoy = Field()  # DISPOSAL_LONGASSET_LOSS_YOY 处置长期资产损失同比
    fa_scrap_loss_yoy = Field()  # FA_SCRAP_LOSS_YOY 固定资产报废损失同比
    fairvalue_change_loss_yoy = Field()  # FAIRVALUE_CHANGE_LOSS_YOY 公允价值变动损失同比
    finance_expense_yoy = Field()  # FINANCE_EXPENSE_YOY 财务费用同比
    invest_loss_yoy = Field()  # INVEST_LOSS_YOY 投资损失同比
    defer_tax_yoy = Field()  # DEFER_TAX_YOY 递延所得税同比
    dt_asset_reduce_yoy = Field()  # DT_ASSET_REDUCE_YOY 递延所得税资产减少额同比
    dt_liab_add_yoy = Field()  # DT_LIAB_ADD_YOY 递延所得税负债增加额同比
    predict_liab_add_yoy = Field()  # PREDICT_LIAB_ADD_YOY 预计负债增加额同比
    inventory_reduce_yoy = Field()  # INVENTORY_REDUCE_YOY 存货减少额同比
    operate_rece_reduce_yoy = Field()  # OPERATE_RECE_REDUCE_YOY 经营性应收项目减少额同比
    operate_payable_add_yoy = Field()  # OPERATE_PAYABLE_ADD_YOY 经营性应付项目增加额同比
    other_yoy = Field()  # OTHER_YOY 其他调整项同比
    operate_netcash_othernote_yoy = Field()  # OPERATE_NETCASH_OTHERNOTE_YOY 经营活动净现金流其他调整项同比
    operate_netcash_balancenote_yoy = Field()  # OPERATE_NETCASH_BALANCENOTE_YOY 经营活动净现金流余额调整项同比
    netcash_operatenote_yoy = Field()  # NETCASH_OPERATENOTE_YOY 经营活动净现金流调整总额同比
    debt_transfer_capital_yoy = Field()  # DEBT_TRANSFER_CAPITAL_YOY 债务转为资本的现金同比
    convert_bond_1year_yoy = Field()  # CONVERT_BOND_1YEAR_YOY 一年内到期的可转换公司债券同比
    finlease_obtain_fa_yoy = Field()  # FINLEASE_OBTAIN_FA_YOY 融资租赁取得的固定资产同比
    uninvolve_investfin_other_yoy = Field()  # UNINVOLVE_INVESTFIN_OTHER_YOY 不涉及投资和筹资的现金其他项同比
    end_cash_yoy = Field()  # END_CASH_YOY 期末现金余额同比
    begin_cash_yoy = Field()  # BEGIN_CASH_YOY 期初现金余额同比
    end_cash_equivalents_yoy = Field()  # END_CASH_EQUIVALENTS_YOY 期末现金等价物余额同比
    begin_cash_equivalents_yoy = Field()  # BEGIN_CASH_EQUIVALENTS_YOY 期初现金等价物余额同比
    cce_add_othernote_yoy = Field()  # CCE_ADD_OTHERNOTE_YOY 现金及现金等价物增加额其他调整项同比
    cce_add_balancenote_yoy = Field()  # CCE_ADD_BALANCENOTE_YOY 现金及现金等价物增加额余额调整项同比
    cce_addnote_yoy = Field()  # CCE_ADDNOTE_YOY 现金及现金等价物增加额调整总额同比
    opinion_type = Field()  # OPINION_TYPE 审计意见类型
    osopinion_type = Field()  # OSOPINION_TYPE 其他审计意见类型
    minority_interest = Field()  # MINORITY_INTEREST 少数股东损益
    minority_interest_yoy = Field()  # MINORITY_INTEREST_YOY 少数股东损益同比
    useright_asset_amortize = Field()  # USERIGHT_ASSET_AMORTIZE 使用权资产摊销
    useright_asset_amortize_yoy = Field()  # USERIGHT_ASSET_AMORTIZE_YOY 使用权资产摊销同比


class SeniorExecutivesItem(Item):
    pmid  = Field() # （stock_code + name）MD5 32位 业务主键、唯一索引
    stock_code  = Field() # 股票代码
    stock_name  = Field() # 股票名称
    name  = Field() # 姓名
    gender  = Field() # 性别
    age  = Field() #
    education  = Field() # 学历
    shareholding_num  = Field() # 持股数 (股)
    salary  = Field() # 薪酬 (元)
    position  = Field() # 职务
    tenure_start_date = Field() # 任职开始时间
    tenure_end_date  = Field() # 任职结束时间
    introduction  = Field() # 高管简介 text 类型


class ListedExecutiveChangesItem(Item):
    pmid = Field()
    change_date = Field() # 变动日期
    stock_code = Field() # 股票代码
    stock_name = Field() # 股票名称
    changer = Field() # 变动人
    change_shares = Field() # 变动股数
    average_trading_price = Field() # 成交均价
    change_amount = Field() # 变动金额（万）
    change_reason = Field() # 变动原因
    change_ratio = Field() # 变动比例（%）
    shares_after_change = Field() # 变动后持股数
    share_type = Field() # 持股种类
    supervisor_name = Field() # 董监高人员姓名
    position = Field() # 职务
    relationship_with_supervisor = Field() # 变动人与董监高的关系
